apache/singa

Makefile.example, include/trainer/trainer.h, include/trainer/worker.h, src/trainer/trainer.cc
There are two bugs on ZeroMq:
1. zsys_init: Assertion `!s_process_ctx' failed
2. zsock_connect( ) fail for inproc communication
The first one is caused by multiple threads calling zsys_init function concurrently.  ZeroMQ restricts the order of binding and connect for inproc communication. 
http://api.zeromq.org/4-0:zmq-connect says that "The first exception is when using the inproc:// transport: you must call zmq_bind() before calling zmq_connect()."
http://api.zeromq.org/4-0:zmq-connect says that "The first exception is when using the inproc:// transport: you must call zmq_bind() before calling zmq_connect()."
The second one is because the endpoint to connect has not bind yet. The comments for zsys_init is as follows,
//  Initialize CZMQ zsys layer; this happens automatically when you …
=> [SINGA-2] Fix bugs about zsock_connect and zsys_init

Makefile.am, Makefile.in, README.md
Modify Makefile.am to support advanced compilation. Add corresponding guidance in README.
=> SINGA-13 Separate intermediate files of compilation from source files

include/trainer/worker.h, src/trainer/trainer.cc, src/trainer/worker.cc
The ConnectStub function wraps the ping-pong messages for connecting worker dealers (including the dealer for transferring parameters and the dealer for transferring features) with the stub router.
The bug comes from that we fixed the entity type to kWorkerParam. Consequently, it can only work for one dealer. The other dealer then gets stuck. It happens when we need to transfer features between workers, e.g., model partitioning as shown in the [quick start page](http://singa.incubator.apache.org/quick-start.html).
=> SINGA-15 Fixg a bug from ConnectStub function which gets stuck for connecting layer_dealer_

examples/cifar10/cluster.conf, include/neuralnet/base_layer.h, include/neuralnet/layer.h, src/neuralnet/base_layer.cc, src/neuralnet/layer.cc, src/proto/model.proto, src/trainer/worker.cc
Replace the boolean type variable "training" in ComputeFeature function (and other functions) with Phase type variable "phase". This update is to support the training of different models, e.g., RBM, and feed forward models like CNN. Phase can be kTrain (for training phase), kTest (for test phase),
kPositive (for positive phase of the contrastive divergence algorithm), etc.
=> SINGA-14 Update layer API to be general for training different models

examples/cifar10/model.conf, include/communication/msg.h, include/trainer/server.h, include/trainer/trainer.h, include/utils/cluster.h, include/utils/common.h, include/utils/param.h, src/communication/msg.cc, src/neuralnet/layer.cc, src/proto/cluster.proto, src/proto/model.proto, src/trainer/server.cc, src/trainer/trainer.cc, src/trainer/worker.cc, src/utils/cluster.cc, src/utils/common.cc, src/utils/param.cc
Some Param objects in deep learning models are much larger than other Param objects. For example, a weight matrix is usually 100 times larger than a bias vector. The difference in Param size causes two problems,
1. if there are multiple servers in one server group, then the servers may be assigned different number of parameters to update.
2. if there are multiple server groups, e.g., in distributed Hogwild framework, then these server groups may be assigned different number of parameters to maintain.
This ticket its to slice large Param objects to solve the load-balance problem. 
A simple slicing algorithm is used to make it possible to partition all sliced objects into m boxes such that all boxes are assigned similar size of parameters. Because these sliced objects may be partitioned …
=> SINGA-19 Slice large Param objects for load-balance

include/trainer/trainer.h, include/utils/blob.h, src/trainer/server.cc, src/trainer/trainer.cc, src/trainer/worker.cc, src/utils/blob.cc, src/utils/cluster.cc, src/utils/param.cc
Downpour training framwork has multiple worker groups and single server groups.
Note: Param slices of servers would share memory space with local workers.
If the local worker is not from group 0 who does the put requests, but it has Param slices in local servers,
then it has to tell local servers in the Get requests the pointers for the shared slices's memory space.
Tested with worker_server_separate= true and false, server/worker group with one and more workers.
To run with 2 process, config the cluster.conf as:
nworker_groups: 2    
nservers_per_group: 2
We can also separate the workers and servers into different process by configuring cluster.conf as (all other fields are default to 1):
server_worker_separate: true
start one process as,
./bin/singa-run.sh …
=> SINGA-24 Implement Downpour training framework

include/utils/common.h, src/main.cc, src/proto/cluster.proto, src/trainer/server.cc, src/trainer/worker.cc, src/utils/common.cc
Glog's default output folder is /tmp/, which may have a lot of files and makes it not convenient to find recent logs.
This ticket is to set the log files under <workspace>/log/ folder, where workspace is configured in cluster.conf.
The log file name is 
<model name>-<log level>-<date time>
=> SINGA-25 - Setup glog output path

src/utils/graph.cc
There is a bug in the Sort function of graph.cc,
which would push one node into the 'tmp' queue for
multiple times if this node has multiple source nodes.
Solution: use an unordered_set to store all nodes in the queue;
push a node only when it is not in the 'tmp' queue.
=> SINGA-28 Fix a bug from toplogy sort of Graph

include/communication/msg.h, include/communication/socket.h, include/neuralnet/base_layer.h, include/neuralnet/neuralnet.h, include/trainer/server.h, include/trainer/trainer.h, include/trainer/worker.h, include/utils/common.h, include/utils/param.h, include/utils/updater.h, src/communication/msg.cc, src/communication/socket.cc, src/neuralnet/layer.cc, src/neuralnet/neuralnet.cc, src/proto/model.proto, src/test/test_paramslicer.cc, src/test/test_shard.cc, src/trainer/server.cc, src/trainer/trainer.cc, src/trainer/worker.cc, src/utils/cluster.cc, src/utils/common.cc, src/utils/param.cc
For the synchronous training frameworks, one worker group and one server group are launched.
Gradients for the same Param are aggregated locally at each process's stub.    The server conducts update until receive all gradients for the same Param (slice). After udpate, the server sends back new Param (slice) values to every process who has sent update request.    The worker_shard_ and server_shard consist of ParamEntrys, each of which stores the information of one unique Param (slice), e.g.,    the number of shares of each Param (slice), and the local shares for each Param (slice).
The Msg class is improved to have clean/simple API. The msg header now includes a src (int), a dst (int) and a trgt (int value and int version),    representing the source addr, destination addr and target of …
=> SINGA-32  Implement AllReduce training framework

bin/singa-run.sh, examples/cifar10/cluster-dist.conf, examples/cifar10/model.conf, include/neuralnet/layer.h, include/trainer/trainer.h, include/trainer/worker.h, include/utils/blob.h, include/utils/cluster.h, include/utils/param.h, src/main.cc, src/neuralnet/layer.cc, src/neuralnet/neuralnet.cc, src/proto/common.proto, src/proto/model.proto, src/trainer/trainer.cc, src/trainer/worker.cc, src/utils/blob.cc, src/utils/cluster.cc, src/utils/param.cc
The checkpoint is done in the Worker class and controlled by two model configuration fields: checkpoint_after and checkpoint_frequency.
Only do checkpoint for the Params owning the param values from the first group. The name, version and values of one Param are dumped onto disk (the path is <workspace>/checkpoint/step<training step>-worker<worker id>.bin). It is possible that the snapshot is separated into multiple files because the neural net is partitioned into multi workers.
The checkpoint files can be used:
* application 1: to restore (resume) the training by setting the command line argument -resume = true.
The Resume function of the Trainer will find the files for the latest snapshot and add them to the model.conf's checkpoint filed. It also set the model config's step field to the …
=> SINGA-12 Supprt Checkpoint and Restore

.gitignore, bin/singa-cleanup.sh, bin/singa-console.sh, bin/singa-env.sh, bin/singa-run.sh, bin/zk-service.sh, include/trainer/trainer.h, include/utils/cluster.h, include/utils/cluster_rt.h, src/main.cc, src/trainer/trainer.cc, src/trainer/worker.cc, src/utils/cluster.cc, src/utils/cluster_rt.cc, src/utils/tool.cc, tool/gen_hosts.py
After supporting concurrent jobs, SINGA could be used in following ways:
1. Quick Run
This is for whose who just want to test singa or run a single job.
* start a singa job
$./bin/singa-run.sh -conf=CONF_DIR
* stop singa
$./bin/singa-stop.sh
* remove all singa-related data
$./bin/singa-cleanup.sh
2. Multi-Job Management
This is for whose who want to manage multiple jobs in a cluster.
In this case you should first:
- edit host file in conf/hostfile
- edit zookeeper host in conf/singa.conf
- make your ssh command password-free
* start a singa job
$./bin/singa-run.sh -conf=CONF_DIR
* list/view/kill singa jobs
$./bin/singa-console.sh list
$./bin/singa-console.sh view JOB_ID
$./bin/singa-console.sh kill JOB_ID
* stop entire singa
$./bin/singa-stop.sh
* remove all singa-related data …
=> SINGA-38 Support concurrent jobs

src/neuralnet/layer.cc, src/proto/job.proto, src/trainer/trainer.cc, src/trainer/worker.cc
Fixbug this bug arising from calling Worker::Put() in Worker::InitLocalParam().
Previously, the version/step passed to Put() is step_ which starts from ModelProto::step.
Hence, the params in the servers are put with version step_. When the params are load from checkpoint files and their param versions are not reset, then the trainining may get stuck after one iteration. Because if the start step is small (usually 0), parame version at the server side is small (i.e., 0), while the local_version() (assigned from version()) is the one from last checkpoint, which is large. Hence the Worker::Collect() function will get stuck. To fix this bug, just pass the current param->version() to Worker::Put().
Update default value for ModelProto::reset_param_version to true. It will reset all parameter …
=> SINGA-42 Issue when loading checkpoints

Makefile.example, examples/cifar10/job.conf, src/utils/param.cc
The Param::HandlePutMsg doesn't set the weight decay multiplier and learning rate multiplier correctly.
The previous code doesn't use the values from the received messages.
Fixed the bug using the correct multipliers.
=> SINGA-49 Fix a bug in HandlePutMsg func that sets param fields to invalid values

src/utils/common.cc
When reseting the values of Metric object, we didn't use reference which made the resetting invalid.
Fixed the bug by using reference.
=> SINGA-44 Fix a bug in reseting metric values

include/neuralnet/layer.h, include/neuralnet/optional_layer.h, src/neuralnet/layer.cc, src/neuralnet/neuralnet.cc, src/neuralnet/optional_layer.cc
The bug is fixed by closing the data source (e.g., lmdb or datashard) after reading a sample record in the Setup function.
The data source would cache memory which eat up all memory if there are many data layers.
=> SINGA-47 Fix a bug in data layers that leads to out-of-memory when group size is too large

bin/singa-cleanup.sh, bin/singa-console.sh, bin/singa-env.sh, bin/singa-run.sh, bin/singa-stop.sh, examples/cifar10/job.conf, include/utils/cluster_rt.h, src/main.cc, src/proto/job.proto, src/proto/singa.proto, src/utils/cluster_rt.cc, src/utils/tool.cc
singa-run script now only takes a job.conf as input (instead of workspace)
users are required to set a workspace in their job.conf
all job information are recorded in the log_dir, which is set in singa.conf
the dir structure is as follows:
log_dir/job-info/job-ID-YYYYmmdd-HHMMSS/job.hosts     host list
/job.pids       pid list
=> SINGA-43 Remove Job-related output from workspace

include/singa.h, src/proto/job.proto
Add a configuration field (openblas_num_threads) in JobProto which specifies the num of threads used by openblas, default to 1.
If multiple workers/servers are launched in one process, this field must be set to 1 (according to openblas wiki page).
=> SINGA-45 Set openblas num threads in job configuration

bin/singa-cleanup.sh, bin/singa-console.sh, bin/singa-env.sh, bin/singa-run.sh, bin/singa-stop.sh, bin/zk-service.sh, include/utils/cluster_rt.h, src/utils/cluster_rt.cc, src/utils/tool.cc
disabled launching zk service in singa-run.sh
users need to explicitly start zookeeper
if use zk in /thirdparty, /bin/zk-service can be used to start/stop it
functionality of scripts are minor changed:
- singa-cleanup.sh now will not stop zookeeper
- singa-stop.sh now only remove /singa/app path in zk,
so it will not reset future job id to start from 0
=> SINGA-56 No automatic launching of zookeeper service

examples/cifar10/job.conf, examples/mnist/conv.conf, examples/mnist/job.conf, include/driver.h, include/trainer/worker.h, include/utils/param.h, include/utils/updater.h, src/driver.cc, src/proto/job.proto, src/trainer/server.cc, src/trainer/worker.cc, src/utils/param.cc, src/utils/updater.cc
The learning rate of SGD typically changes through time.
There are many different ways to change the learning rate of SGD. SINGA has implemented a couple of changing methods. But users may want to implement their own changing method. To make this part modular, this ticket is going to create a base learning rate generator, e.g. called LRGenerator, which is declared like,
class LRGenerator {
public:
virtual float Get (int step) = 0;
protected:
LRProto proto_;
};
Users can then inherit LRGenerator to implement the their own changing algorithm in the `Get(int step)`. Users can also add configurations for their generator by extending the base LRGenProto.
Similarly, we make the parameter initialization modular by creating a base class ParamGenerator which has a function tot initialize parameter …
=> SINGA-60 Make learning rate and param init modular

Makefile.am, configure.ac, examples/cifar10/job.conf, examples/mnist/conv.conf, examples/mnist/job.conf, examples/rbm/autoencoder.conf, examples/rbm/rbm0.conf, examples/rbm/rbm1.conf, examples/rbm/rbm2.conf, examples/rbm/rbm3.conf, include/mshadow/tensor_random.h, include/neuralnet/base_layer.h, include/neuralnet/layer.h, include/trainer/worker.h, include/utils/param.h, src/driver.cc, src/neuralnet/base_layer.cc, src/neuralnet/layer.cc, src/proto/job.proto, src/trainer/worker.cc, src/utils/common.cc, src/utils/param.cc
This is to implement RBM in SINGA.
To training RBM models, the Contrastive Divergence (CD) algorithm is implemented.
We have implemented a BPWorker to run the Back-Propagation algorithm. To implement the CD algorithm, we follow the same way
to create a CDWorker whose RunOneBatch function controls the logic of the CD algorithm, including positive phase,
negative phase and computing gradient phase. RBM's layers are different to the layers for feed-forward neural networks,
hence new layers for RBM models are added.
=> SINGA-9 Add Support for Restricted Boltzman Machine (RBM) model

src/proto/job.proto, src/trainer/worker.cc
Add checks for test_net_ and validation_net_ (!=nullptr) before conduct
testing and validation.
Set default values (1) to nworker_groups and nserver_groups.
=> SINGA-66 Fix bugs in Worker::RunOneBatch function and ClusterProto

Makefile.am, configure.ac
Modified Makefile.am to add a target named "singatest".
Now "make" will generate 5 files/libs: libsinga.la libgtest.la singa singatool singatest.
User can also specify the target he wants to generate, for example, "make singa".
=> SINGA-67 Add singatest into build targets

examples/cifar10/job.conf, include/trainer/server.h, include/trainer/trainer.h, include/utils/cluster.h, src/proto/common.proto, src/proto/job.proto, src/trainer/server.cc, src/trainer/trainer.cc, src/utils/cluster.cc
The Trainer::Run and Server::Run was messy due to the monitoring of the network bandwidth for implementing the distributed hogwild. This pull request re-implement this framework removing the bandwidth monitoring.
The ClusterProto::sync_freq field controls the frequency of sync between
server groups.
After updating of Param (slice), the server checks the num of updates
since last sync. It also checks the num of pending syncs (i.e., requests
haven't received reponses) to avoid sending too many msgs to stopped
servers (the msgs would be occupy the memory of the sending buffer)
The server respones to every sync requests with the latest Param values.
Note: current does not support (there is bug) multiple worker groups in
one process for the distributed hogwild framework. We recommend to …
=> SINGA-57 Improve Distributed Hogwild

Makefile.am, rat-excludes
(Thanks Zhongle for the help with the Makefile.am)
Apache RAT enables automatic checking of license headers in source files. SINGA supports RAT by adding
a target into the Makefile, and providing a `rat-excludes` file at the top-level directory.
Specifically, the `make rat` target does the following:
+ Check for java and Apache RAT .jar file in the $RAT_PATH variable.
+ Invoke `make clean`
+ Invoke RAT and write the output to `rat_check` file.
Notice the side-effect of `make rat` that removes all built files. Thus, it is recommended to use before
building the source.
=> SINGA-77 Integrate with Apache RAT

bin/singa-env.sh, conf/singa.conf, include/utils/cluster_rt.h, src/utils/cluster_rt.cc, src/utils/tool.cc
To test the code, please go to arbitrary directory, and execute scripts in bin, e.g. zk-service.sh, to see if they can run properly.
singa-env.sh
- change commandline arg from -confdir= to -conf
tool.cc
- parse -conf flag to read corresponding sing configure
cluster_rt.h/cc
- add detailed documentation for JobManager
- add checks for zk related operations if zk handler is not initilized.
=> SINGA-79 Fix bug in singatool that can not parse -conf flag

Makefile.am, examples/cifar10/job.conf, include/singa/neuralnet/neuron_layer/argsort.h, include/singa/neuralnet/neuron_layer/softmax.h, include/singa/neuralnet/output_layer/record.h, src/driver.cc, src/neuralnet/loss_layer/softmax.cc, src/neuralnet/neuron_layer/argsort.cc, src/neuralnet/neuron_layer/softmax.cc, src/proto/job.proto
SoftmaxLayer applies the Softmax function against its source layer to compute its probability distribution over all labels.
ArgSortLayer sorts labels based on their scores (e.g., probability) in descending order.
Configuration for ArgSortLayer is like 
argsort_conf{ 
topk: 1
}
Topk results will be extracted.
Connecting ArgSortLayer to a CSVOutputLayer, we can dump the topk labels of each instance into one line. 
To test this feature using the cifar10 example, please comment out the SoftmaxLossLayer and add SoftmaxLayer (kSoftmax), ArgSortLayer (kArgSort) and CSVOutputLayer (kCSVOutput).
=> SINGA-91 - Add SoftmaxLayer and ArgSortLayer to dump prediction results

src/comm/socket.cc
I think the asterisk is unnecessary in the log as follows:
I1016 11:45:58.958664 3862 socket.cc:123] bind successfully to tcp://169.254.12.152:*:49152.
It's better to remove it.
=> [SINGA-93] Remove the asterisk in the log tcp://169.254.12.152:*:49152

src/driver.cc, src/main.cc
It appears that google::InitGoogleLogging() was never intended to be called inside a library.
The reason is because calling google::InitGoogleLogging() twice results in program termination with the error log "You called InitGoogleLogging() twice!".
Calling google::InitGoogleLogging() inside Driver::Init() prevents users of the Singa library from making this call in their own main() function, as recommended by glog documentation.
=> SINGA-94 Move call to google::InitGoogleLogging() from Driver::Init() to main().

tool/mesos/Makefile, tool/mesos/README.md, tool/mesos/scheduler.conf, tool/mesos/scheduler.proto, tool/mesos/singa.conf, tool/mesos/singa_scheduler.cc
Apache Mesos is a fine-grained cluster management framework which enables resource sharing in the same cluster. Mesos abstracts out the physical configurations of cluster nodes, and presents resources to the users in the form of "offers". SINGA uses Mesos for two purposes:
1. To acquire necessary resources for training the model.
2. To launch and monitor progress of the training task.
To this end, we implement a "SINGA Scheduler" which interacts with Mesos master. The scheduler assumes that SINGA has been installed  at the Mesos slave nodes. The scheduler is called when the user wants to start a new SINGA job, and it performs the following steps:
Step 1. Read the job configuration file to determine necessary resources in terms of CPUs, memory and storage.
Step 2. Wait for resource offers …
=> SINGA-11 Start SINGA on Apache Mesos

tool/docker/README.md, tool/docker/mesos/.bashrc, tool/docker/mesos/.vimrc, tool/docker/mesos/Dockerfile, tool/docker/mesos/core-site.xml, tool/docker/mesos/hdfs-site.xml, tool/docker/mesos/install.sh, tool/docker/mesos/mapred-site.xml, tool/docker/mesos/yarn-site.xml, tool/docker/singa/.bashrc, tool/docker/singa/.vimrc, tool/docker/singa/Dockerfile, tool/docker/singa/ssh.conf
Docker is a Linux container which is fast to deploy and incurs small overhead. A Docker container functions like a light-weight virtual machine and runs in its own isolated environment. There are at least two benefits in building adding Docker support for SINGA:
+ Out of the box deployment of SINGA: the image, once built, contains the complete environment necessary to start SINGA.
+ Light-weight development and testing environment for distributed features. The image can be used to set up a test-bed consisting of many independent nodes (each node has its own IP address), without the need for cluster hardware.
We add to Github a Dockerfile specifying how to build SINGA image, from which the user can construct the image by executing:
sudo docker build -t singa/base .
The user can choose …
=> SINGA-89  Add Docker support

Makefile.am, configure.ac
Add a new target named "test". Users just run "make test" and the system will finish the compilation and execution of the test.
=> SINGA-95 Add make test after building

tool/docker/mesos/.bashrc, tool/docker/singa/.bashrc
Root loads docker containers while the command ll (ls -l) cannot be found. However ll is handier than ls -l.
#91
=> [SINGA-101] Add ll (ls -l) command in .bashrc file when using docker

Makefile.am, include/singa/neuralnet/connection_layer/bridge.h, include/singa/neuralnet/neuron_layer/dummy.h, include/singa/worker.h, src/neuralnet/connection_layer/bridge.cc, src/neuralnet/neuron_layer/dummy.cc, src/proto/job.proto, src/test/test_connection_layers.cc, src/worker.cc
re-implement bridge layers for model partition
* move socket operations for sending/receiving blobs from worker into layers,
so that it is transparent to users who will implment TrainOneBatch
* when initialing worker, it will create a socket instance and pass it to all
bridge layers using layer.MakePaired() function
SINGA-106 dummy layer also included
dummy layer can be used as input, neuron, output layer to construct a simple
neuralnet when only focusing on testing a specific layer
To test, just 'make test'
test_connection_layers.cc contains test for both bridge layer and dummy layer
=> SINGA-109 Refine bridge layers

include/singa/neuralnet/connection_layer.h, include/singa/neuralnet/neuralnet.h, include/singa/utils/common.h, include/singa/utils/graph.h, src/driver.cc, src/neuralnet/connection_layer/slice.cc, src/neuralnet/connection_layer/split.cc, src/neuralnet/layer.cc, src/neuralnet/neuralnet.cc, src/utils/common.cc, src/utils/graph.cc, src/worker.cc
* Updated the Graph class to format the string representation in ToJson function.
* The Layer::ToString function is updated to generate string for debug info, e.g., layer data and gradient norm.
* Insert code to collect debug info from layers forward and backward function in BPWorker class.
* Add NeuralNet::ToGraph function to convert a neualnet into a Graph which can converted into a string using ToJson function.
To test this pull request,
1. run the cifar10 example, get the `train_net.json` file from `example/cifar10/visualization/`, visualize the neural net by 
python tool/graph.py examples/cifar10/visualization/train_net.json train_net.jpg
2. run the cifar10 example for a few steps without test and with debug enabled. 
// job.conf 
train_steps: 5
test_steps: 0
debug: true
Visualize …
=> SINGA-115 - Print layer debug information in the neural net graph file

src/neuralnet/neuron_layer/inner_product.cc, src/neuralnet/neuron_layer/rbm.cc, src/utils/param.cc
There is a bug in the implementation of InnerProductLayer, which appears when training the auto-encoder example.
The weight matrix in inner-product layer in the encoder is shared by another layer in the decoder. But the decoder uses transposed version.
The current code does not handle matrix transposition.
The bug can be fixed considering the transpose_ field explicitly.
We may later handle it implicitly using a Tensor class that handles transposition automatically.
To test this pull request, run the rbm example.
=> SINGA-116 Fix a bug in InnerProductLayer caused by weight matrix sharing

.gitignore, src/driver.cc, src/proto/job.proto
We init log dir before calling cluster setup, so that it will not generate a short log in tmp dir.
clean ids in job.conf:
- Input Layer:      100 - 199
- Neuron Layer:     200 - 299
- Loss Layer:       300 - 399
- Output Layer:     400 - 499
- Connection Layer: 500 - 599
=> SINGA-114, 118 improvement on log dir and layer type id

Makefile.am
Generate a new library named "libsingagpu.so" linking math_kernel.o via NVCC and link it into libsinga.so via libtool(gcc).
=> SINGA-121 Not linking math_kernel.o when generate libsinga.so

Makefile.am, configure.ac, examples/cifar10/Makefile.example, examples/cifar10/create_data.cc, examples/mnist/Makefile.example, examples/mnist/create_data.cc, include/singa/io/hdfs_store.h, include/singa/io/hdfsfile.h, include/singa/io/kvfile_store.h, include/singa/io/store.h, include/singa/io/textfile_store.h, src/io/hdfsfile.cc, src/io/hdfsfile_store.cc, src/io/kvfile_store.cc, src/io/store.cc
This ticket implements HDFS Store for reading data from HDFS. It complements
the existing CSV Store which reads data from CSV file. HDFS is the popular
distributed file system with high (sequential) I/O throughputs, thus supporting
it is necessary in order for SINGA to scale.
HDFS usage in SINGA is different to that in standard MapReduce applications.
Specifically, each SINGA worker may train on sequences of records which do not
lie within block boundary, whereas in MapReduce  each Mapper process a number
of complete blocks.  In MapReduce, the runtime engine may fetch and cache the
entire block over the network, knowing that the block will be processed
entirely. In SINGA, such pre-fetching and caching strategy will be sub-optimal
because it wastes I/O and network bandwidth on data records …
=> SINGA-97 Add HDFS Store

src/neuralnet/neuron_layer/convolution.cc
The order of parameters is not correct when function Im2col and Col2im are called.
=> SINGA-139 Fixed a bug in built-in convolution layer

Makefile.am
Docker build failed during `make install`.
The error is caused by the `install-pyLTLIBRARIES` target in the Makefile fails to check for the
exitence of `.libs/_driver.so`.
The fix simply adds the the check to `Makefile.am`.
=> SINGA-149 Docker build fail

tool/docker/mesos/Dockerfile, tool/docker/singa/Dockerfile, tool/docker/singa/Dockerfile_gpu, tool/mesos/singa_scheduler.cc
The initial ticket was raised when executing SINGA using Mesos containers threw exception
`called InitGoogleLoggin() twice`
This issue contains fixes for the initial problem, plus refactoring of the
Docker build process. A new Dockerfile is added to build GPU-enabled
SINGA. We also update the documentation for building SINGA containers,
since new versions of Docker have removed features that the we depended on.
Particularly, since Docker 1.9, launching new containers will not update
`/etc/hosts` files on the existing containers, causing name resolution to fail.
=> SINGA-150 Mesos Docker container failed

include/singa/utils/context.h, include/singa/utils/math_blob.h, src/worker.cc
The worker may query the device id before the driver sets it up (via Context).  It is fixed by sleeping the worker until the driver finishes the setting.  Now all devices (GPU and CPU) must be setup via Context::SetupDevice, otherwise the worker would sleep forever. The Blob math functions now check device_id < 0 to call CPU/GPU functions.
=> SINGA-148 Race condition between Worker threads and Driver

Makefile.am, configure.ac, include/singa/utils/cluster_rt.h, include/singa/utils/job_manager.h, include/singa/utils/zk_service.h, src/utils/cluster.cc, src/utils/cluster_rt.cc, src/utils/job_manager.cc, src/utils/tool.cc, src/utils/zk_service.cc
Make zookeeper a optional dependency.
By default, we only support single-process training.
To enable distributed training, please install zookeeper and configure with:
./configure --enable-zookeeper
=> SINGA-155 Remove zookeeper for single-process training

Makefile.am, configure.ac, include/singa/comm/msg.h, include/singa/comm/socket.h, include/singa/server.h, include/singa/utils/safe_queue.h, src/comm/msg.cc, src/comm/socket.cc, src/driver.cc, src/server.cc, src/stub.cc, src/utils/cluster_rt.cc, src/utils/param.cc, src/worker.cc
SINGA depends on ZMQ and CZMQ, which are used for intra and inter process communication.
In fact, for training using a single process (with multiple threads), we can avoid ZMQ and CZMQ for intra-process communication. 
This ticket implements the intra-process communication by assigning a thread-safe queue for each socket (i.e., dealer and router). The sender pushes the msg onto the receiver's queue. In this way, we can remove the dependency on ZMQ and CZMQ for single process training.
There is a macro 'USE_ZMQ', which controls the compiling of ZMQ related code. If USE_ZMQ is not defined, SINGA can only run for single process. Otherwise, SINGA uses ZMQ for inter-process communication and uses the msg queues for intra-process communication.
=> SINGA-156 Remove the dependency on ZMQ for single process training

bin/singa-run.sh, include/singa/driver.h, include/singa/stub.h, include/singa/utils/cluster.h, src/driver.cc, src/stub.cc, src/utils/cluster.cc
Minor changes to extend the single node Multi-GPU training to the GPU
cluster scenario.
1. remove gethostip which is not stable (only work for some OS). Now users have to config the hostfile with each line specifying the IP (must be IP) of one node.
2. register process id no matter the running environment.
3. the singa-run.sh has to `source` the '.profile' ('.bashrc' does not wrok) file right before
executing singa, which exports the LD_LIBRARY_PATH for the cudnn and cuda library. There is no problem if singa is compiled without cuda.
To test this feature,
1. export the path to cudnn and cuda in LD_LIBRARY_PATH in `.profile`
2. compile with cudnn, cuda and `--enable-dist`.
3. set the zookeeper url in conf/singa.conf
4. add the IP of each node in conf/hostfile (must use IP)
5. set ssh …
=> SINGA-134 Extend SINGA to run over a GPU cluster

src/neuralnet/input_layer/store.cc, src/proto/job.proto
Allow users set the batchsize of instances of StoreInputLayer manually.
We can then assign different workload for GPU and CPU workers who have
different input layers, e.g.,
```
batchsize: 128
batchsize: 16
```
If the first worker is GPU and the second worker is CPU, then the
above setting would assign 128 images per mini-batch to the GPU worker
and assign 16 images to the CPU worker.
Internally, StoreInputLayer gets its batchsize based on its partition ID.
Currently, it works for MNIST example which has no Conv layers.
For Conv layers, since the GPU and CPU implementations have different
layer names, we cannot using the single net config.
To test this feature, change the cudnn.conf
```
test_steps: 0
{ // train data layer
batchsize: 128
batchsize: 16
}
{ // cluster
nworkers_per_group: 2 …
```
=> SINGA-131 Implement and optimize hybrid training using both CPU and GPU

Makefile.am, configure.ac, include/singa/neuralnet/neuron_layer.h, src/driver.cc, src/neuralnet/neuron_layer/cudnn_bm.cc, tool/docker/singa/Dockerfile_gpu
If the cudnn.h is in cuda/include folder, then the --with-cudnn is invalid as cuda/include is looked up first. We need to change the order of these two paths during compilation. On the other hand, we also need to put libsingagpu.so file into a proper folder to make our scripts runnable.
=> Singa-157 Change the priority of cudnn library and install libsingagpu.so

include/singa/utils/channel.h, src/utils/channel.cc, test/singa/test_channel.cc
Add utils/channel.h, utils/channel.cc, test/test_channel.cc
Channel provides functionalities of unifily sending training statistics
to different terminals.
Upon setup, config it in global:
InitChannel();
SetChannelDirectory(path);
To get channel instance:
GetChannel(channel_name);
Then send messages:
channel->Send(message);
=> SINGA-195 Channel for sending training statistics

include/singa/model/initializer.h, test/singa/test_initializer.cc
5 initialization methods are added, namely, constant, uniform, gaussian,
Xavier (also called glorot) and MSRA.
We use the same config fields as Caffe, hence we simply rename Caffe's protobuf
message to FillerConf. The base class is singa::init::Initializer. To
avoid name conflicts with Uniform and Gaussian methods, we enclose them
into the namespace init. May consider rename them later.
=> SINGA-187 Add popular parameter initialization methods

include/singa/core/common.h, include/singa/core/tensor.h, src/core/tensor/tensor.cc, test/singa/test_tensor_math.cc
Update the Block class to add the `offset_` field and change the type of
ref_count_ to shared_ptr<atomic<int>>.
Now, we can share the ref_count_ and data_ between different Blocks.
It is useful if Block A is a sub-block of Blokc B, i.e., Block A's data() is Block B's data() + offset.
This feature is not used currently.
Implement CopyRows, CopyColumns, ConcatenateRows and ConcatenateColumns.
SliceRows() is not implmented yet, which may affect the block management
(some blocks sharing internal data).
=> SINGA-205 - Enable slice and concatenate operations for Tensor objects

include/singa/core/tensor.h, include/singa/io/snapshot.h, src/core/tensor/tensor.cc, src/io/snapshot.cc, src/proto/core.proto, test/singa/test_snapshot.cc
This ticket is going to add code for dumping the model parameters as
checkpoint files, which could be used for fine-tuning and deployment.
Serialize Tensor into TensorProto and save it in BinFile, which is
stored as <prefix>.model, and generate description about parameters
in <prefix>.desc.
Unit test cases passed for kFloat, kInt and kDouble data type.
=> SINGA-210 Enable checkpoint and resume for v1.0

include/singa/io/reader.h, include/singa/io/writer.h, src/io/binfile_reader.cc, src/io/lmdb_reader.cc, src/io/lmdb_writer.cc, src/io/textfile_reader.cc, test/singa/test_lmdb_rw.cc, test/singa/test_textfile_rw.cc
Add LMDBReader and LMDBWriter for LMDB. The classes are modified from db_lmdb.cpp and db_lmdb.hpp in Caffe.
Need to swith "USE_LMDB" ON when using these two classes.
Todo: LMDB does not support checking empty and duplicate keys, may support by us later.
=> SINGA-214 Add LMDBReader and LMDBWriter for LMDB

include/singa/core/device.h, include/singa/core/memory.h, include/singa/utils/cuda_utils.h, src/core/device/cpp_cpu.cc, src/core/device/cuda_gpu.cc, src/core/device/device.cc, src/core/device/platform.cc, src/core/memory/memory.cc, src/proto/core.proto, src/python/swig/core_device.i, test/singa/test_cpp_cpu.cc, test/singa/test_cudnn_activation.cc, test/singa/test_cudnn_batchnorm.cc, test/singa/test_cudnn_convolution.cc, test/singa/test_cudnn_dropout.cc, test/singa/test_cudnn_lrn.cc, test/singa/test_cudnn_pooling.cc, test/singa/test_cudnn_softmax.cc, test/singa/test_dense.cc, test/singa/test_memory.cc, test/singa/test_platform.cc, test/singa/test_tensor.cc
Add the Platform class whose methods are all static.
It includes methods for query hardware GPUs, e.g., num of gpus, memory of each gpu.
It also creats a vector of singa::Device, e.g., CudaGPU.
NOTE:
If multiple CudaGPU devices are created, and they all use CnMemPool,
then they must share the same CnMemPool instance (otherwise there would
be problems in desctructing the CnMemPool).
It is preferred to use Platform to create CudaGPU devices which would
avoid the above problem.
Updated the APIs for Device and DeviceMemPool.
The GetAllocateMem is not accurate (which is larger than actually requested memory size).
=> SINGA-194 Add a Platform singleton

CMakeLists.txt, include/singa/io/transformer.h, src/io/image_transformer.cc, src/io/jpg_decoder.cc, src/proto/io.proto, test/singa/test_activation.cc, test/singa/test_cpp_cpu.cc, test/singa/test_cudnn_activation.cc, test/singa/test_cudnn_softmax.cc, test/singa/test_image_transformer.cc, test/singa/test_jpg.cc, test/singa/test_mse.cc, test/singa/test_prelu.cc, test/singa/test_softmax.cc
Implement some of the image transformations (i.e., crop, resize, horizontal_mirror) for pre-processing stage.
Image resize need to use opencv library.
Currently image transformation only support one sample input each time.
Add static function resize, crop and mirror for image transformation.
Training phase use random crop and random mirror,
Evaluation phase use central crop and no mirror.
Cannot test phases for mirror because of a random factor.
Fix bugs in test files involving memory allocation and access.
=> SINGA-215 Implement Image Transformation for Image Pre-processing

examples/cifar10/train.py, examples/cifar10/vgg.py, src/model/layer/cudnn_batchnorm.cc, test/singa/test_cudnn_batchnorm.cc
Revise cifar10 example to support batchnormalized vgg model trainning
on CPU.
Now parameters of Batch Normalization layer are 1D tensor
both in GPU and CPU version.
=> SINGA-174 Add Batch Normalization layer and Local Response Nomalization

examples/cifar10/predict.py, examples/cifar10/train.py, python/singa/net.py, python/singa/snapshot.py, src/api/io_snapshot.i, src/proto/core.proto
Use the snapshot methods to dump and load models for pysinga to make the
model checkpoint slimmer.
Previously we use Pickle to checkpoint in pysinga, which make the
model checkpoints heavier than using io/snapshot which leveraging
protobuf to serialize parameters of models.
=> SINGA-252 Use the snapshot methods to dump and load models for pysinga

python/singa/data.py, python/singa/image_tool.py, python/singa/layer.py
Add ImageBatchIter in data.py, which prefetches images into mini-batches
and pre-processes images using user defined transform function.
The process is done in another process via multiprocessing
fixed a bug in merge layer which should replicate the gradients in the returned values
To test this feature,
please prepare a train.txt file which consists of multiple lines, where each line is <image_path><space><image_label>, e.g.
```
image1.jpg, 0
image2.jpg, 3
image3.jpg, 1
...
```
The folder should be like 
```
SINGA ROOT/
train.txt
images/
image1.jpg
image2.jpg
...
```
Then you can run python python/singa/data.py  (under the root dir of singa).
After that, you should see a list of images which are transformed from the images in images/ folder.
=> SINGA-251 - Implement image loader for pysinga

examples/cifar10/train.py, include/singa/core/tensor.h, include/singa/model/optimizer.h, python/singa/layer.py, python/singa/optimizer.py, python/singa/tensor.py, src/api/model_optimizer.i, src/model/layer/batchnorm.cc, src/model/layer/cudnn_batchnorm.cc, src/model/optimizer/adagrad.cc, src/model/optimizer/nesterov.cc, src/model/optimizer/optimizer.cc, src/model/optimizer/rmsprop.cc, src/model/optimizer/sgd.cc
Implemented Adam for pysinga.
Added an argument to control the applying of regularization and constraint
for parameters, which is necessary for BN layers as the mean and std
should not be updated by updaters. The effect is not obvious for other
udpaters, but is very significant for Adam.
Tested Adam for alexnet on cifar10, and the accuracy was 0.8 (SGD is
0.82); It was also not as good as SGD on VGG net (0.92); May need to
tune the learning rate.
To test this PR, 
1. please replace the optimizer from SGD to Adam in examples/cifar10/train.py
2. pass a constant learning rate (e.g 0.01) to apply_with_lr, instead of the learning rate generation function
3. add the iteration ID as the last argument of apply_with_lr.
=> SINGA-254 Implement Adam for V1

examples/cifar10/README.md, examples/cifar10/caffe/caffe_net.py, examples/cifar10/caffe/cifar10_full_solver.prototxt, examples/cifar10/caffe/cifar10_full_train_test.prototxt, examples/cifar10/caffe/cifar10_quick_solver.prototxt, examples/cifar10/caffe/cifar10_quick_train_test.prototxt, examples/cifar10/train.py, python/singa/converter.py, python/singa/layer.py, src/model/layer/pooling.cc, src/proto/caffe.proto, src/proto/model.proto
Convert caffe model into singa model.
It is a very basic implementation. Now it can convert feed forward net and supports pysinga.
Implementation method:
1. read proto file of caffe model using caffe.proto, and serialize it to string.
2. parse the string use singa model.proto and get the layer config.
3. setup each layer and add it to a feed forward net.
Update and example:
1. put conversion funcions into layer.py and converter.py;
2. add 'caffe' option in cifar example which converts alexnet from
caffe to singa.
=> SINGA-253 Net converter for caffe model

src/model/layer/batchnorm.cc, src/model/layer/cudnn_batchnorm.cc
Added spatial mode in batch normalization layer in C++ implementation,
which corresponds to CUDNN_BATCHNORM_SPATIAL in CuDNN.
Also added logics to automatically detect proper modes in batch
normalization layer, i.e., if input is 2D tensor then batchnorm
layer chooses PER_ACTIVATION mode, if input is 4D tensor then
batchnorm layer chooses SPATIAL mode.
=> SINGA-267 Add spatial mode in batch normalization layer

python/singa/layer.py, python/singa/net.py, src/api/model_layer.i, test/python/run.py, test/python/test_net.py
Extend FeedForwardNet to support multiple input tensors and output tensors.
The input variable x, of train(x, y), forward(x), predict(x), evaluate(x)
could be a single tensor or a dictionary: layer name -> a single tensor or tensor list.
The key is the name of the layer to feed the input data.
The output of out=forward(x, output), would be a single tensor or a dictionary:
layer name -> a single tensor or a tensor list. The key is the name of
the layer to get the output values, e.g, the net has multiple layers
whose outgoing degree is 0. By configuring the argument
'output' as a list of layer names, we can get values of those layers in
'out'.
Passed unittests.
=> SINGA-264 Extend the FeedForwardNet to accept multiple inputs

include/singa/core/tensor.h, include/singa/model/loss.h, python/singa/layer.py, python/singa/loss.py, src/core/tensor/math_kernel.cu, src/core/tensor/math_kernel.h, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h, src/model/loss/softmax_cross_entropy.cc, test/python/test_optimizer.py, test/singa/test_cross_entropy.cc
Updated the softmax cross entorpy loss layer and the tensor functions to enable
the ground truth be an binary array for each instance;
Added unittests for cross entropy with multiple labels per instance;
For input of a batch of instances, the ground truth tensor could be either an integer array, one value per
instance, or a binary matrix one row per instance.
For a single instance input, the feature tensor is 1-d array, and the
ground truth tensor is a 1-d array (with a single integer value or a
binary array)
=> SINGA-275 - Add Cross Entropy Loss for multiple labels

test/singa/test_layer.cc
Fixed a bug by removing dropout layer from test_layer unit test when
CUDNN version is 4.0
=> SINGA-279 Unit Test test_layer failed when CUDNN version is 4.0

python/singa/layer.py, python/singa/net.py
1. reversed(list) returns a reversedlistiterator, it should return a list. fixed by using list[::-1]
2. add debugging output for backward function
=> SINGA-283 Fix a bug of net.py backward function for layers with multiple inputs

python/singa/data.py, src/core/device/device.cc, src/core/tensor/tensor.cc, src/model/layer/cudnn_convolution.cc
add warning if the cudnn conv workspace size is too large (>512MB);
add size check when malloc memory for tensor to make sure the size is >=0
=> SINGA-287 - Add memory size check for cudnn convolution

.travis.yml
remove the command for installing glog in travis.yml to make it clear
that glog is an optional dependency of buidling and running SINGA.
=> SINGA-299 - Remove glog from travis.yml

examples/imagenet/resnet/README.md, examples/imagenet/resnet/convert.py, examples/imagenet/resnet/model.py, examples/imagenet/resnet/serve.py, python/singa/device.py, python/singa/layer.py, python/singa/net.py, src/model/layer/convolution.cc, src/model/layer/convolution.h, src/model/layer/cudnn_convolution.cc, src/model/layer/dense.cc, src/model/layer/dense.h
This PR adds a couple of residual networks trained over ImageNet. Pre-trained parameters from torch are converted into python dictionary and dumped via cPickle.
In particular, the following residual networks are implemented
1. Original residual network https://arxiv.org/abs/1512.03385
2. Pre-activation residual network https://arxiv.org/abs/1603.05027
3. Wide residual network http://arxiv.org/abs/1605.07146
Refer to the README file for testing this PR.
reference:
https://github.com/facebook/fb.resnet.torch
https://github.com/szagoruyko/wide-residual-networks
=> SINGA-300 Add residual networks for imagenet classification

tool/travis/build.sh, tool/travis/conda.sh, tool/travis/depends.sh
Updated the .travis.yml file and added scripts in tool/travis folder.
Test on osx and linux
TODO: add conda scripts for building conda packages for SINGA on Travis
(linux and osx).
=> SINGA-302 - Extend the travis config for building SINGA on OSX

README.md, doc/en/docs/cnn.md, doc/en/releases/RELEASE_NOTES_0.1.0.md, doc/en/releases/RELEASE_NOTES_0.2.0.md, doc/en/releases/RELEASE_NOTES_0.3.0.md, doc/en/releases/RELEASE_NOTES_1.0.0.md, doc/en/releases/RELEASE_NOTES_1.1.0.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
=> Fix broken headings in Markdown files

examples/imagenet/resnet/README.md, python/singa/data.py
To read the image list file which contains only the image path per line.
The returned value of function next() consists of x (ndarray of images)
and y([None] * batchsize).
=>  SINGA-318 - Extend ImageBatchIter to read image list file without meta info

src/model/layer/cudnn_batchnorm.cc
When size of batch-normalization layer and dense layer doesn't match, here is one error that may pop up when run "examples/cifar-10/train.py", which should look like:
[tensor.h: 99] Check failed: idx < shape_.size() (2 vs. 2)
By modifying the code, this problem should have been fixed.
=> Fix the size-not-match problem when batch-normalization layer connect to dense layer

python/singa/net.py
Without replacing gradients with its average over matrix's size, they are going to be too high to maintain a stable loss. Typically, I found this bug when run alexnet using examples/cifar10/train.py. The loss stays at around 87 without dropping.
=> Average gradients otherwise loss overflows in examples/cifar10/train.py

doc/en/docs/installation.md, tool/conda/meta.yaml
update tool/conda/meta.yaml for the versions of dependent libs for compilation and running.
update the FAQ for 'No module named _singa_wrap'
=> SINGA-325 - Fix the bug of numpy version mis-match

src/model/layer/cudnn_rnn.cc, src/model/layer/rnn.h
The cudnn rnn layer is updated to handle mini-batches with
different seq lengths. The internal data structures are re-allocated if
max_length_ < seq_length_ (the longest sample of the current
mini-batch).
=> SINGA-324 Extend RNN layer to accept variant seq length across batches

python/singa/tensor.py
Tensor division operation error resulted in failure of backward propagation when training CNN models.
Change division to multiplication of the inverse.
=> SINGA-331 Fix the bug of tensor division operation

include/singa/core/tensor.h, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h
converted some upper-case functions to lower-case
fixed return types for some non-void cuda functions
added check_cudnn to check for CUDNN_STATUS_SUCCESS for all cudnn functions
removal of set_strides usage in cuda file and replacement with additional cudnn transform functions
updated all unary and binary cuda functions for transform
updated reshape function to return tensor
fixed FromProto function by removing original reshape
change to reshape to support in-place operations as well as return new tensor
added constructors for Transform function (GenUnaryTensorFn) similar to cudnn's transform function
updated tensor_math.h for transform
added Transform function for cpp and cuda
added Transform to reshape instead of add
=> SINGA-370 Improvement to tensor reshape and various misc. changes related to SINGA-341 and 351

tool/conda/cpu/meta.yaml, tool/conda/gpu/meta.yaml, tool/conda/singa/meta.yaml
The depdency rule on protobuf is relax to >= 3.2.0 (from == 3.2.0)
=> SINGA-396 Upgrade `protobuf` to 3.6.1 to match Tensorflow's

tool/conda/singa/meta.yaml
It is due to the version mismatch of Protobuf.
In SINGA-396, we updated the protobuf version to be >=3.2.0. And the
singa package is built using 3.2.0.
However, 3.6.1 is installed in your OS. In other words, the runtime env
and the building env mismatch.
In this commit, we fix the version for both building and runtime to
3.6.1.
=> SINGA-409 [Singa 1.2.0] Basic `singa-cpu` import throws error

doc/en/docs/install_win.rst, doc/en/docs/security.rst, doc/en/index.rst
This commit closes the issue with the minimal solution. But more work will be needed in future to improve SINGA security.
It includes also fixing little typing mistakes in install_win.rst
=> SINGA-417 #close adding a link to Apache Security page

python/singa/autograd.py, test/python/test_operation.py
Add 3 operators , Abs(), Exp() and leakyrelu(), for Autograd Layer class
=> SINGA-425 Add 3 operators

src/core/tensor/tensor.cc, test/singa/test_cross_entropy.cc, test/singa/test_mse.cc, test/singa/test_tensor_math.cc
*fix bug:
- allow reshaping on an empty tensor then give it data will invoke segmentation fault.
*how to fix:
- when reshape, add a check requiring the original shape's volume must be same with new one.
- fix corresponding test case(test_mse, test_cross_entropy, test_tensor_math)
=> *fix bug: segmentation fault at test case

src/model/operation/batchnorm.cc, test/singa/test_cross_entropy.cc, test/singa/test_tensor.cc
Hi teams,
This is to fix some broken `Reshape` after adding a extra restriction on reshaping.
After this fix, unit_test all passing by directly compiling against updated dockerfile except `Tensor.T` test, which is discussed at: https://github.com/apache/incubator-singa/pull/438
=> hf:reshape error

tool/conda/docker/cuda10/Dockerfile, tool/conda/docker/cuda9/Dockerfile, tool/conda/singa/meta.yaml
Add py36 or py37 to the build string of conda packages
Update the docker file for conda build by removing cudnn
=> SINGA-460 - Build packages for Py36 and Py37

python/singa/tensor.py
Improve the `__itruediv__ `operation by using the /= operator of c tensor (i.e tensor.data) directly instead of *= operator.
Has tested two cases (because for end to end purpose):
Case 1. simple tensor division in ncrf docker container
```python
from singa import tensor
from singa import device
import numpy as np
Y = np.ones(shape=[10],dtype=np.float32) * 10.0
y = tensor.from_numpy(Y)
y.to_device(device.get_default_device())
y.to_device(device.create_cuda_gpu_on(1))
def divide(y):
y /= 10
divide(y)
print(tensor.to_numpy(y))
```
Result
```
root@26c9db193eb0:~/incubator-singa# python3 /root/incubator-singa/python/singa/test.py
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
```
Case 2. 8 GPUs mnist distributed training in AWS (i.e. mnist_dist_demo.py)
```
ubuntu@ip-172-31-17-155:~$ …
```
=> SINGA-478 Improve __itruediv__ in tensor.py

examples/autograd/mnist_cnn.py, examples/autograd/mnist_multiprocess.py, include/singa/io/communicator.h, python/singa/opt.py, src/api/dist_communicator.i, src/io/communicator.cc
I have added the support for the Python Multiprocess Module for single-node multi-gpu scanerio. 
For the old MPI-based NCCL, I have also simplified and cleaned the code, where I removed the nDev variable (i.e. number of GPU controlled by each process) which is always 1 in our case.
So, in the following autograd example, 
(i)  mnist_multiprocess.py is the example using python multiprocessing module
(ii)  mnist_dist.py is the example using MPI for multiprocessing
Note that the speed is about the same comparing MPI and the python multiprocessing module. (Multiprocessing module maybe slightly faster than MPI)
The results for both examples are as follows:
```
ubuntu@ip-172-31-38-62:~/incubator-singa/examples/autograd$ python3 mnist_multiprocess.py
Training loss = 801.480042, …
```
=> SINGA-487 Add the support of Python Multiprocess Module

.travis.yml, doc/en/develop/build.md
Using [Codecov Bash Uploader](https://docs.codecov.io/docs/about-the-codecov-bash-uploader) with Travis CI to upload coverage information to codecov.io .
=> SINGA-485 Add code coverage with codecov

examples/autograd/mnist_cnn.py, examples/autograd/resnet.py, examples/autograd/resnet_dist.py, examples/autograd/xceptionnet.py, examples/imagenet/googlenet/serve.py, examples/imagenet/resnet/model.py, examples/mnist/train.py, python/singa/autograd.py, python/singa/image_tool.py, python/singa/optimizer.py, python/singa/sonnx.py, python/singa/tensor.py, src/core/tensor/tensor_math_cpp.h, src/model/layer/convolution.cc, tool/opencl/clsrc_to_str.py
Since LGTM has been applied for our code analysis (see SINGA-484), I have cleaned up many of the obvious issues alerted by LGTM.
The compile result is okay as follows:
```
ubuntu@ip-172-31-39-137:~/incubator-singa/build$ rm -rf *
ubuntu@ip-172-31-39-137:~/incubator-singa/build$ cmake -D CMAKE_PREFIX_PATH="/usr/local/cuda/lib64;/usr/local/                          cuda/" -DENABLE_TEST=OFF -DUSE_CUDA=ON -DUSE_PYTHON3=ON -DUSE_MKLDNN=ON -DUSE_MODULES=OFF -DUSE_DIST=ON ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile …
```
=> SINGA-491 Code Cleaning with the Reference of LGTM Analysis Result

tool/conda/singa/meta.yaml
This will fix the issue in "SINGA-488 Travis CI always build from Apache master branch"
=> SINGA-488 Change the path of source code for CI

src/model/layer/batchnorm.h, src/model/layer/convolution.h, src/model/layer/dense.h, src/model/layer/prelu.h
This is to fix the remaining C language alert from LGTM: 
There are some functions using ResetLike and CopyData to copy the data from the tensor input. This PR changes the input type from "Tensor" to "const Tensor&"
However, it seems that the src/model/layer is used by the old optimizer/model, it does not have effect on the autograd.py based model.
If I am correct, this avoid the system copying the input tensor with the tensor copy constructor, instead it uses the address of the input pointer as reference.
For a verification, the batchnorm in src/model/layer is used by the old optimizer (not the autograd one), and hence we use the old resnet example to verify the training loss reduction progress.
```
ubuntu@ip-172-31-42-250:~/incubator-singa/examples/cifar10$ python3 train.py resnet …
```
=> SINGA-491 Use const reference for CopyData and ResetLike from Tensor Input

doc/en/index.rst
The added message is :
"SINGA was graduated as a Top-Level Project (TLP) of the Apache Software Foundation in October 2019."
The built webpage looks like this:
=> SINGA-493 Update news: SINGA graduation as a TLP

examples/autograd/mnist_cnn.py, examples/autograd/resnet_dist.py, include/singa/io/communicator.h, python/singa/opt.py, src/api/dist_communicator.i, src/io/communicator.cc
This PR deals with the Parallelization of Computation and Communication using CUDA stream concurrency, which can reduce the communication overhead.
Together with the result of PR #555, here is a simple test to make sure the training is correct:
```
ubuntu@ip-172-31-29-119:~/singa/examples/autograd$ /home/ubuntu/mpich-3.3/build/bin/mpiexec --hostfile host_file python3 mnist_dist.py
Training loss = 931.969849, training accuracy = 0.675197
Evaluation accuracy = 0.913137, Elapsed Time = 0.733470s
Training loss = 280.136505, training accuracy = 0.910273
Evaluation accuracy = 0.954975, Elapsed Time = 0.642032s
Training loss = 188.183517, training accuracy = 0.939837
Evaluation accuracy = 0.967619, Elapsed Time = 0.650523s …
```
=> SINGA-487 Parallelize Comp. and Comm. using CUDA stream concurrency

.gitignore
current doc-site generated files are not git checked, thus proposed this gitignore update
=> update gitignore for Sphinx-Doxygen doc built files

doc/en/community/team-list.rst
Change PPMC to PMC
Remove "Mentors" since SINGA is graduated now from the incubator. All the mentors are now part of the PMC.
Add Xiangrui Cai as committer
Correct Sheng Wang status from PPMC to committer (I think a vote is required to add him as PMC)
Order all names alphabetically
=> SINGA-493 Update team page

examples/autograd/mnist_cnn.py, examples/autograd/resnet_dist.py, include/singa/io/communicator.h, python/singa/opt.py, src/api/dist_communicator.i, src/io/communicator.cc
This PR reduces the network latency by fusing gradients in the same memory buffer before sending out with NCCL.
This can reduce much of the TCP/IP latency by reducing the number of NCCL API call.
Together with the result of PR #555, here is a simple test to make sure the training is correct:
```
ubuntu@ip-172-31-26-214:~/singa/examples/autograd$ python3 mnist_multiprocess.py
Training loss = 831.072205, training accuracy = 0.700454
Evaluation accuracy = 0.927015, Elapsed Time = 0.676089s
Training loss = 248.684601, training accuracy = 0.916183
Evaluation accuracy = 0.958265, Elapsed Time = 0.545179s
Training loss = 172.330597, training accuracy = 0.943042
Evaluation accuracy = 0.967928, Elapsed Time = 0.543617s …
```
=> SINGA-487 Fusing gradients to reduce network latency

python/singa/autograd.py, src/core/device/cuda_gpu.cc, src/core/tensor/math_kernel.cu
The performance is improved after some optimization on GPU Malloc and Cudastream:
See the performance (1) after, and (2) before the modification
(1) After Modification:
```
ubuntu@ip-172-31-34-140:~/singa/examples/autograd$ python3 mnist_cnn.py
Training loss = 588.176819, training accuracy = 0.791072
Evaluation accuracy = 0.940405, Elapsed Time = 4.002963s
Training loss = 231.185471, training accuracy = 0.923209
Evaluation accuracy = 0.956631, Elapsed Time = 3.601223s
Training loss = 161.976379, training accuracy = 0.946438
Evaluation accuracy = 0.960537, Elapsed Time = 3.605442s
Training loss = 134.834137, training accuracy = 0.955460
Evaluation accuracy = 0.968249, Elapsed Time = 3.614901s
Starting Epoch 4:
Training …
```
=> SINGA-490 Optimization on GPU Malloc and Cudastream

include/singa/io/communicator.h, python/singa/opt.py, src/api/dist_communicator.i, src/core/tensor/math_kernel.cu, src/core/tensor/math_kernel.h, src/io/communicator.cc
In this PR, I add an API in opt.py for using half precision in gradient transfer.
Here is the training accurate test using 16 bit for gradient transfer:
ubuntu@ip-172-31-29-33:~/singa/examples/autograd$ /home/ubuntu/mpich-3.3/build/bin/mpiexec --hostfile host_file python3 mnist_dist.py
Training loss = 790.405762, training accuracy = 0.715144
Evaluation accuracy = 0.928557, Elapsed Time = 0.675930s
Training loss = 252.329041, training accuracy = 0.915181
Evaluation accuracy = 0.961143, Elapsed Time = 0.545467s
Training loss = 181.895905, training accuracy = 0.938618
Evaluation accuracy = 0.965461, Elapsed Time = 0.554351s
Training loss = 136.416214, training accuracy = 0.954577
Evaluation accuracy = 0.970806, Elapsed …
=> SINGA-487 Add support of gradient compression to half precision

include/singa/core/tensor.h, python/singa/autograd.py, src/api/core_tensor.i, src/core/tensor/math_kernel.cu, src/core/tensor/math_kernel.h, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h, test/python/test_operation.py
This PR deals with two issues: 1. Improve ReLU, 2. Optimize Add, Sub, EltwiseMult after the last update with broadcasting:
1. The ReLU function exists in every layers of CNN structures, so we can speed up CNN by improving the computational efficiency of ReLU
The existing ReLU function function uses a FP32 multiplication to work with a floating point binary mask:
```python
def backward(self, dy):
dx = singa.GTFloat(self.input, 0.0)
dx *= dy
return dx
```
The new implementation is much more simple and efficient:
If the ReLU input in forward function > 0,  it copys the output gradient vlaue; If not, we assign 0 value:
```cpp
__global__ void KernelReLUBackward(const size_t n, const float *in1, const float *in2,
float *out) {
for (size_t i = blockIdx.x * blockDim.x + threadIdx.x; i < n;
i += …
```
=> SINGA-490 Improve Efficiency of ReLU, Add, Sub, EltwiseMult

python/singa/autograd.py, python/singa/sonnx.py
Previously I moved the bias and scale of batch norm operators from the forward function to its init function,  however, this caused the number of inputs is different from the number of backward return tensor. Now I restore the batchnorm to its previous version and also fix the onnx accordingly.
=> Bug fix: restore batchnorm

examples/autograd/mlp.py, src/core/tensor/tensor.cc, src/core/tensor/tensor_math_cuda.h, test/python/test_api.py
moved `softmax(..., axis)` implementation one level up, from cuda to tensor. After the change, `softmax(..., axis)` implemenation could serve for both cuda and cpp. Tested is added accordingly.
=> hotfix: cpp softmax not impl

include/singa/core/tensor.h, python/singa/tensor.py, src/core/tensor/tensor.cc, src/core/tensor/tensor_math_cpp.h, test/python/test_tensor.py, tool/docker/devel/ubuntu/cpu/Dockerfile, tool/docker/devel/ubuntu/cuda10/Dockerfile, tool/docker/devel/ubuntu/cuda9/Dockerfile
1. added additional word to indicate mutation on underline data
2. add inplace flag to indicate mutation on underline data
3. updated cpp `sum()` on axis
4. no change to python `add_column()` or similar as it could be done by `broadcast` and could be deprecated.
=> Tensor naming convention review

include/singa/core/tensor.h, python/singa/autograd.py, src/api/core_tensor.i, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h
The softmax_cross_entropy move to data to host and then back to gpu, so the whole function needed to be changed for many reasons such as efficiency and asynchronization (and buffering operation in the future). :
class SoftMaxCrossEntropy(Operation): 
def _init_(self, t): 
super(SoftMaxCrossEntropy, self)._init_() 
self.t = t.data
def forward(self, x): 
self.p = singa.SoftMax 
loss = CTensor((1,), self.p.device()) 
ret = singa.CrossEntropyFwd(self.p, self.t) 
loss.SetFloatValue(singa.SumAsFloat(ret) / x.shape()[0]) 
return loss
Here the SumAsFloat return a c++ float value, and this value is read back to gpu in the SetFloatValue function.
=> SINGA-502 Avoid moving data between host and gpu in SoftmaxCrossEntropy

python/singa/autograd.py, test/python/test_operation.py
I have fixed the bugs in autograd.py and update test case mentioned in issue #576 
The results are ok now:
```
ubuntu@ip-172-31-24-48:~/singa/test/python$ python3 test_operation.py
.............................................................................................................................
Ran 125 tests in 0.624s
OK
ubuntu@ip-172-31-24-48:~/singa/test/python$ cd ..
ubuntu@ip-172-31-24-48:~/singa/test$ cd ..
ubuntu@ip-172-31-24-48:~/singa$ cd examples
ubuntu@ip-172-31-24-48:~/singa/examples$ cd autograd
ubuntu@ip-172-31-24-48:~/singa/examples/autograd$ python3 mlp.py
train_data_shape: (400, 2)
train_label_shape: (400, 2)
training loss =  0.6905591
training loss =  0.5654273
training loss =  0.54077435 …
```
=> hotfix: bugs in autograd.py and also update test case

src/model/operation/batchnorm.cc
There is an new error in cpu batchnorm, where the number of output arguments do not match with the python autograd code. This PR simply fix the issue.
```
root@b8dfa5473dea:~/dcsysh/singa/test/python# python3 test_operation.py
................................................................E............................................................
======================================================================
ERROR: test_batchnorm2d_cpu (__main__.TestPythonOperation)
Traceback (most recent call last):
File "test_operation.py", line 286, in test_batchnorm2d_cpu
y = batchnorm_0(cpu_input_tensor)
File "/root/dcsysh/singa/build/python/singa/autograd.py", line 1502, in __call__
self.running_var,
File …
```
=> Bugfix: cpu batchnorm (num of args does not match)

include/singa/core/tensor.h, python/singa/autograd.py, src/api/core_tensor.i, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h, test/python/test_api.py
The current SoftMax backward is using numpy, which cannot be buffered.
This PR uses cudnn and dnnl SoftMaxBackward instead of numpy.
=> SINGA-505 SoftMax Backward to be bufferable

src/core/tensor/tensor_math_cuda.h
Here I change the algorithm of the cudnnSoftmaxForward function.
The original algorithm was CUDNN_SOFTMAX_FAST which may lead to overflow when the input numbers are too large. Change it to CUDNN_SOFTMAX_ACCURATE will solve this problem.
For example: If cudnn softmax is used in mlp.py, it will lead to this problem.
=> fix softmax nan problem

tool/docker/devel/ubuntu/cuda10/Dockerfile, tool/docker/devel/ubuntu/cuda9/Dockerfile
In dockerfile, this fix registers the mpiexec command in environment variable path automatically
Before this fix it needs to add the path of the mpi binary manually
=> Fix the env path to include mpiexec

.asf.yaml
The Apache infrastructe supports [new features for git](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=127405038) with .asf.yaml file. 
In this pull request, we improve the description and labels of SINGA github. 
Labels are important because they allow github users to navigate and explore github repositores with [Topics](https://github.com/topics). I added one topic "deep learning", but we may add also other related topics such as python3, docker, cpp, rest-api, machine-learning, ... etc.
An example for .asf.yaml in Apache ShardingSphere is [here](https://github.com/apache/incubator-shardingsphere/blob/master/.asf.yaml).
The .asf.yaml can be added also to [singa-site](https://github.com/apache/singa-site) to enable the new features for site deployment.
=> SINGA-415 add asf.yaml file

python/singa/autograd.py, python/singa/utils.py, test/python/test_operation.py
Since onnx requests same padding mode, we need to optimize conv and pooling these 2 operators.
FYI:
> auto_pad must be either NOTSET, SAME_UPPER, SAME_LOWER or VALID. Where default value is NOTSET, which means explicit padding is used. SAME_UPPER or SAME_LOWER mean pad the input so that the output spatial size match the input.In case of odd number add the extra padding at the end for SAME_UPPER and at the beginning for SAME_LOWER. VALID mean no padding.
This JR will finish:
- lower-level ops(_Conv2d and _Pooling2d) support odd padding mode, for example, if padding is [2,5,2,5], it will crop to a normal padding with [2,2,2,2], and a odd padding with [0,3,0,3]. The odd padding will be added to x tensor firstly and then do normal process with normal padding, then in the backward, the odd …
=> Singa 507 _Conv2d and _Pooling2d support odd padding

.asf.yaml
@nudles , I remember that you wanted to enable github wiki as discussed [here](https://issues.apache.org/jira/browse/SINGA-405?focusedCommentId=16699087&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16699087). We can now have github wiki by adding the following in the asf.yaml file.
=> SINGA-415 Enable github wiki

python/singa/device.py, python/singa/module.py, src/core/scheduler/scheduler.cc, src/core/tensor/tensor.cc, src/model/operation/batchnorm.cc, src/model/operation/convolution.cc, src/model/operation/pooling.cc
Capture some tensors by value. These tensors will be recycled during the evaluation phase. But this PR may affect memory usage when enabling graph.
=> Improve graph compatibility

src/core/device/device.cc, src/core/scheduler/scheduler.cc, src/core/tensor/tensor.cc, test/singa/test_cross_entropy.cc, test/singa/test_platform.cc, test/singa/test_snapshot.cc
* Fix bugs of buffering Mult.
* Can train ResNet50 with batch size of 64 now.
=> Fix bugs of training

examples/rnn/train.py, include/singa/core/scheduler.h, python/singa/module.py, src/core/scheduler/scheduler.cc, test/singa/test_scheduler.cc
In this pr, I have fixed some bugs for automatic recycling. This is due to incorrect dependency analysis when using the same tensor for multiple operations when executing programs in the order of DFS. Now, the RNN model in the examples dir can be trained in graph mode.
Besides, I also optimized the Analysis function, Debug function, and the structure of the graph.
=> fix bugs of recycling

examples/cnn/train.py, examples/cnn/train_mpi.py, examples/cnn/train_multiprocess.py, include/singa/core/device.h, include/singa/core/scheduler.h, src/api/core_device.i, src/core/device/cpp_cpu.cc, src/core/device/cuda_gpu.cc, src/core/device/device.cc, src/core/scheduler/scheduler.cc, src/core/tensor/tensor.cc, src/io/communicator.cc, src/model/layer/cudnn_activation.cc, src/model/layer/cudnn_convolution.cc, src/model/layer/cudnn_dropout.cc, src/model/operation/batchnorm.cc, src/model/operation/convolution.cc, src/model/operation/pooling.cc, test/singa/test_cpp_cpu.cc
Time Profiling for single GPU:
verbosity level: 0 (default) -> no logging
verbosity level: 1 -> forward and backward propagation time 
verbosity level: 2 -> each operation time (OP_ID, operation name, time)
The time is displayed as the average per iteration.
```
root@831960763a12:~/dcsysh/singa/examples/cnn# python3 train.py cnn mnist --verbosity 1
Training loss = 578.907959, training accuracy = 0.796141
Evaluation accuracy = 0.937400, Elapsed Time = 5.622292s
Training loss = 232.124695, training accuracy = 0.922609
Evaluation accuracy = 0.962841, Elapsed Time = 5.603526s
Training loss = 167.437912, training accuracy = 0.944220
Evaluation accuracy = 0.971855, Elapsed Time = 5.422868s
Training loss = 138.634125, …
```
=> SINGA-510 Add Time Profiling for Single GPU

examples/cnn/benchmark.py, include/singa/core/device.h, include/singa/core/scheduler.h, src/api/core_device.i, src/core/device/cpp_cpu.cc, src/core/device/cuda_gpu.cc, src/core/device/device.cc, src/core/scheduler/scheduler.cc
There are several improvement in the time profiling function
1.  Greatly reduced the measurement overhead: In the new version, we synchronize the cudastream only one time at the end of iteration. The previous version needs to synchronize cudastream whenever it measures each operation, so it introduced time overhead.
2. Can skip the initial iterations for time profiling. It can be set using the function SetSkipIteration, while the default is 5 iterations.
3. Modify the benchmark.py for resnet 50 benchmark time profiling.
=> SINGA-510 Improvement of Time Profiling Function

tool/conda/dist/meta.yaml, tool/conda/docker/cuda10.2/Dockerfile, tool/conda/gpu/meta.yaml, tool/conda/singa/conda_build_config.yaml, tool/docker/devel/ubuntu/cuda10/Dockerfile, tool/docker/devel/ubuntu/cuda9/Dockerfile
I see some other frameworks have updated their cudnn to 7.6.
Our cudnn version is quite old, so I modify the version of cudnn from 7.3.1 to 7.6.5 (in conda env as well as docker env). Therefore, when we do performance analysis, we can base on same/similar version of cudnn.
Meanswhile, the speed seems does not change, compared in panda13 (cuda 10.2).
Test environment: Conda
(i) cudnn 7.3.1
```
(singapy36) dcsysh@panda13:~/singa/examples/cnn$ python3 benchmark.py
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:13<00:00,  7.56it/s]
Throughput = 241.5528073484408 per second
TotalTime=13.247620820999146
Total=0.13247620820999145
```
(ii) cudnn 7.6.5
```
(singapy36cudnn765) …
```
=> Upgrade CUDNN version from 7.3.1 to 7.6.5

examples/onnx/vgg19.py
Implemented vgg19 model from onnx model zoo.
onnx model reference: https://github.com/onnx/models/tree/master/vision/classification/vgg
Model conversion is done using `sonnx.prepare`
- **Image preprocessing**
Images are loaded in to a range of [0, 1] and then normalised using mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225] as per model specification.
- **Postprocessing**
Output is the softmax probability scores for each class and sorting them to report the top 5 most probable classes.
=> Implement vgg19 model from onnx model zoo

test/python/test_api.py
Here is just a very minor fix of GPU test case, which needs to set the precision of test. 
For instance, the default precision of test is absolute tolerance atol=1e-6 if (we don't pass the argument), which is too tough.
```
root@d05828f767ee:~/dcsysh/singa/test/python# python3 test_api.py
......F.F...................
======================================================================
FAIL: test_batchnorm_testing_gpu (__main__.TestAPI)
Traceback (most recent call last):
File "test_api.py", line 195, in test_batchnorm_testing_gpu
_run_testing(x_0, s_0, b_0, rm_0, rv_0, m_0=1.0)
File "test_api.py", line 186, in _run_testing
y_1, tensor.to_numpy(_cTensor_to_pyTensor(y_2_c)), decimal=5)
File …
```
=> Fix some GPU test cases by precision setting

src/core/device/cuda_gpu.cc, src/core/tensor/math_kernel.cu, tool/conda/singa/meta.yaml
1. When I was building conda package of singa-gpu, I encountered the following error
One available solution is to call `roundf` in CUDA MATH API instead of `std::round `
https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html#group__CUDA__MATH__SINGLE_1ga1c1521079e51b4f54771b16a7f8aeea
With this modification, the round test case can pass:
```
root@e7f452d7c67a:~/dcsysh/singa/test/python# python3 test_api.py
.................................
Ran 33 tests in 1.409s
OK
```
By the way, in the docker version of singa, it does not need this change, maybe it is the difference of GCC version in the two environments.
2. This PR updates the numpy to 1.18.5
3. Seems the `cudaDeviceReset()` in destructor returns …
=> Fix SINGA-gpu conda build and update numpy version

include/singa/core/device.h, python/singa/autograd.py, src/core/device/device.cc
A fix of error in training loss, the expected loss I used for long time is appeared wrong in the dev branch in distributed training,
Before fix:
```
root@64926e30597f:~/dcsysh/singa/examples/cnn# mpiexec -np 3 python3 train_mpi.py cnn mnist -l 0.015
Training loss = 867.269531, training accuracy = 0.682409
Evaluation accuracy = 0.913662, Elapsed Time = 1.374367s
Training loss = 312.582123, training accuracy = 0.893546
Evaluation accuracy = 0.946014, Elapsed Time = 1.324747s
Training loss = 223.973038, training accuracy = 0.924312
Evaluation accuracy = 0.955629, Elapsed Time = 1.325152s
Training loss = 176.310730, training accuracy = 0.939804
Evaluation accuracy = 0.965645, Elapsed Time = 1.327019s
Starting Epoch 4: …
```
=> Fix training loss error

src/core/tensor/tensor.cc, src/core/tensor/tensor_math_cpp.h, test/python/test_tensor.py
added tensor operation type lang pair - cuda kint
fixed tensor operation type lang pair - cpu, kint
fixed tensor operation nrm2 type
added testing for mix type tensor operations
=> tensor operation type lang pair - kInt CPU, cuda

python/singa/sonnx.py
Some adjust to the SONNX logic.
Now, it counts and picks the last layer from the final output layer.
For example, a model's last few layers are:
```
...
|
GlobalAveragePool
|
Flatten
|
Gemm
|
output
```
To get the `output`'s output, set the last_layers=-1
To get the `Gemm`'s output, set the last_layers=-2
To get the `Flatten`'s output, set the last_layers=-3
...
=> fix sonnx last layers

.github/workflows/conda.yaml, test/python/run.py
I used the fix proposed at [PR 457 ](https://github.com/apache/singa/pull/457) and added the Github action to build and test with conda.
As discussed in the PR 457: `This PR is required for enabling the python test with continuous integration. Without this PR, the user must check the error messages of the python test manually by looking at the log and the python test errors are not shown as check errors in Travis CI or Github Actions.`
Currently both Github actions and Travis CI (correctly) fail because of the python test errors.
=> conda build and test with Github Actions

.github/workflows/cpp.yaml, CMakeLists.txt, README.md, src/CMakeLists.txt
Adding C++ code coverage and uploading the report to codecov.io. 
The coverage badge on README shows coverage on Apache master branch, so it will be active when this commit is merged into the master branch. To check coverage on other branches such as dev, simply visit https://codecov.io/gh/apache/singa/ (after merging this PR and completing the github action).
Currently the C++ coverage is around 65%. Later we will add the python code coverage also.
=> Add code coverage for C++

python/singa/autograd.py, python/singa/sonnx.py, test/python/test_onnx_backend.py
Since the ONNX test cases assume it works in an inference environment, so this PR explicitly to enable and disable the training mode before and after the ONNX test cases.
BTW,
Add random seed to dropout operator.
=> Fix test cases error

.codecov.yml, .github/workflows/conda.yaml, .github/workflows/ubuntu.yaml, tool/conda/singa/meta.yaml
Run python test from the conda build and merge the python coverage report with the C++ coverage report. The python coverage ignores the proto directory.
=> code coverage for python

CMakeLists.txt, LICENSE, examples/cnn/train_cnn.py, examples/mlp/module.py, examples/mlp/native.py, include/half.hpp, include/singa/core/common.h, include/singa/core/tensor.h, python/singa/autograd.py, python/singa/layer.py, python/singa/opt.py, python/singa/tensor.py, src/api/core_tensor.i, src/api/numpy.i, src/core/tensor/math_kernel.cu, src/core/tensor/math_kernel.h, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h, src/model/operation/convolution.cc, test/singa/test_operation_benchmark.cc
added half cpp backend, half tensor conversion, half tensor math operations, added half to linear, softmax layer, cnn layers, opt module. tested examples naive, module, train_cnn on mlp and cnn, refactored broadcast, added benchmark for fp16 vs fp32
=> Half float checkpoint

tool/conda/README.md, tool/conda/cpu/README.md, tool/conda/dist/README.md, tool/conda/docker/cpu/Dockerfile, tool/conda/gpu/README.md
This PR has two purposes:
(i) Add a cpu conda build dockerfile, this is useful when the computer does not have gpu but we still want to build cpu package
(ii) Add new readme file on how to generate new conda packages
=> Add new cpu conda build dockerfile and Add new readme

.github/workflows/conda.yaml
Recently, without version locking, the conda-build version is 3.21, where conda build cannot start run for python 3.6, so the test in "conda / build-pytest-package-ubuntu" does not work
Therefore, I lock the version of conda-build to be 3.20.4, it works well as before
=> Fix the conda-build version that does not work recently

examples/cifar_distributed_cnn/train_cnn.py
1. Switch between CPU and GPU devices for cifar_distributed_cnn example
=> Switch between CPU and GPU devices for cifar_distributed_cnn example

examples/model_selection_psql/ms_model_mlp/model.py
Add create model function for the dynamic model
=> Add create model function for the dynamic model

examples/hfl/README.md, examples/hfl/requirements.txt
This pull request creates a horizontal federated learning example using Singa.
=> Create a horizontal federated learning example

examples/hfl/README.md, examples/hfl/src/client.py, examples/hfl/src/server.py
Update descriptions and README.
=> Update the HFL example and README

RELEASE_NOTES
Add the release notes for V 5.0.0
=> Add the release notes for V 5.0.0

examples/healthcare/application/Malaria_Disease/readme.md, examples/healthcare/application/Malaria_Disease/run.sh
Update the running script for the Malaria example
=> Update the running script for the Malaria example

examples/singa_peft/src/singa_peft/peft_registry.py
=> Add the peft registry module

examples/healthcare/application/Hematologic_Disease/readme.md, examples/healthcare/application/Kidney_Disease/README.md, examples/healthcare/application/Thyroid_Eye_Disease/README.md
Update the readme files for the healthcare model zoo
=> Update the readme files for the healthcare model zoo
