include/utils/cluster_rt.h, src/test/test_cluster.cc, src/utils/cluster_rt.cc
Add two new features in ClusterRuntime Class
-- int RegistProc(const string& host_addr)
-- string GetProcHost(int proc_id)
=> SINGA-16 Runtime Process id Management

include/trainer/worker.h, src/trainer/worker.cc
Update the API of TrainOneBatch and TestOneBatch to support different ways of displaying performance metric
=> SINGA-18 update API for displaying performance metric

bin/singa-run.sh, bin/singa-stop.sh, bin/zk-service.sh, examples/cifar10/hostfile, src/trainer/trainer.cc, src/utils/cluster.cc
To run singa in distributed model in a single command, you just use command:
$ ./bin/singa-run.sh -conf=YOUR_CONF_DIR
The provided dir should contain 3 files:
* model.conf
* cluster.conf
* hostfile
Please note that the $zookeeper_host in the cluster.conf should be set as the
host executing this script.
=> SINGA-26 Run distributed training in a single command

bin/singa-run.sh, examples/cifar10/cluster-dist.conf, examples/cifar10/model.conf, examples/mnist/model.conf, include/neuralnet/layer.h, include/trainer/trainer.h, include/trainer/worker.h, include/utils/blob.h, include/utils/cluster.h, include/utils/param.h, include/utils/tinydir.h, src/main.cc, src/neuralnet/layer.cc, src/neuralnet/neuralnet.cc, src/proto/common.proto, src/proto/model.proto, src/test/test_msg.cc, src/test/test_neuralnet.cc, src/trainer/trainer.cc, src/trainer/worker.cc, src/utils/blob.cc, src/utils/cluster.cc, src/utils/param.cc
A share_from field is added into the ParamProto. It indicates the name of the Param that owns the values of this param. The NeuralNet class will then share the data_ Blob from the owner Param. In specific, it will consider share_from firstly and then consider param sharing due to model partition (on dim 0).
For example,
param {
name: "w1"
init_method: kGaussian
std: 0.0001
learning_rate_multiplier: 1.0
}
...
param {
name: "w2"
share_from: "w1"
}
SINGA will copy the configuration of w1 for w2 when preparing the configuration of the neural net.
Later, after setting up each layer, SINGA will  share the data Blob of w1 with w2. If w1 is replicated due to partitioning (on dim 0), w1 will also share its data Blob to w1's replica and w2's replica.
=> SINGA-37 Enable users to set parameter sharing in model configuration 

examples/mnist/rbm_job.conf, include/mshadow/tensor_random.h, include/neuralnet/base_layer.h, include/neuralnet/layer.h, include/trainer/worker.h, src/neuralnet/base_layer.cc, src/neuralnet/layer.cc, src/neuralnet/neuralnet.cc, src/proto/job.proto, src/trainer/trainer.cc, src/trainer/worker.cc, src/utils/graph.cc, src/utils/param.cc
Implement the Contrastive Divergence (CD) algorithm to train RBM model.
We have implemented a BPWorker to run the Back-Propagation algorithm. To implement the CD algorithm, we follow the same way to create a CDWorker whose RunOneBatch function controls the logic of the CD algorithm, including positive phase, negative phase and computing gradient phase.
=> SINGA-9 Add Support for Restricted Boltzman Machine (RBM) model

include/utils/updater.h, src/utils/updater.cc
Scale gradients in Updater::Update() before updating parameters.
Format code in updater.h and updater.cc.
=> SINGA-46 Fix a bug in updater.cc to scale the gradients

src/neuralnet/neuralnet.cc, src/neuralnet/optional_layer.cc, src/trainer/trainer.cc
Cleaned the code for SetupWorkerServer and fixed the bug.
=> SINGA-48 Fix a bug in trainer.cc that assigns the same NeuralNet instance to workers from diff groups

examples/cifar10/job.conf, examples/mnist/conv.conf, examples/mnist/job.conf, include/neuralnet/base_layer.h, include/singa.h, include/trainer/trainer.h, include/trainer/worker.h, src/main.cc, src/neuralnet/base_layer.cc, src/neuralnet/layer.cc, src/neuralnet/neuralnet.cc, src/proto/common.proto, src/proto/job.proto, src/trainer/trainer.cc, src/trainer/worker.cc, src/utils/param.cc
Tested with mnist and cifar examples.
Four components are necessary for submitting a job, namely, neuralnet, alg, updater and cluster.
The configuration is now consistent with the MM paper.
=> SINGA-54 Refactor job configuration to move fields in ModelProto out

include/communication/msg.h, include/communication/socket.h, include/trainer/server.h, include/utils/blob.h, include/utils/cluster.h, include/utils/cluster_rt.h, include/utils/common.h, include/utils/factory.h, include/utils/graph.h, include/utils/param.h, src/communication/msg.cc, src/communication/socket.cc, src/proto/common.proto, src/trainer/server.cc, src/trainer/trainer.cc, src/trainer/worker.cc, src/utils/blob.cc, src/utils/cluster.cc, src/utils/cluster_rt.cc, src/utils/common.cc, src/utils/graph.cc
Following files reviewed:
blob.h, blob.cc
cluster.h, cluster.cc
common.h, common.cc
graph.h, graph.cc
=> SINGA-21 Code review 3

Makefile.am, src/test/test_common.cc
Add the test module for utils/common.cc.
Test function VecToString().
Test function TestStringPrintf().
Test function gcd().
Test function LeastCommonMultiple().
Test class Metric.
Test function Slice.
Test function PartitionSlices().
=> SINGA-64 Add the test module for utils/common

examples/cifar10/job.conf, examples/mnist/conv.conf, include/neuralnet/neuron_layer.h, include/utils/common.h, src/driver.cc, src/neuralnet/neuron_layer.cc, src/proto/job.proto, src/trainer/trainer.cc, src/utils/blob.cc, src/utils/common.cc
Caffe's im2col is adopted to speed up the convolution operation.
The max pooling operation is accelerated by book-keeping the max neuron
position like Caffe.
=> SINGA-51 Improve the convolution and pooling operations

examples/rnnlm/Makefile.example, examples/rnnlm/README.md, examples/rnnlm/create_shard.cc, examples/rnnlm/job.conf, examples/rnnlm/main.cc, examples/rnnlm/rnnlm.cc, examples/rnnlm/rnnlm.h, examples/rnnlm/rnnlm.proto, include/neuralnet/connection_layer.h, include/neuralnet/input_layer.h, include/neuralnet/layer.h, include/utils/common.h, src/neuralnet/input_layer.cc, src/proto/common.proto, src/trainer/worker.cc, src/utils/common.cc, src/utils/tool.cc
Implement RNN for language modelling following http://www.fit.vutbr.cz/~imikolov/rnnlm/.
Need to test the distributed training frameworks on example models to ensure the singatool works correctly.
=> SINGA-10 Add Support for Recurrent Neural Networks (RNN)

include/driver.h, include/neuralnet/neuralnet.h, include/trainer/server.h, include/trainer/trainer.h, include/trainer/worker.h, src/driver.cc, src/main.cc, src/neuralnet/neuralnet.cc, src/trainer/server.cc, src/trainer/trainer.cc, src/trainer/worker.cc
Following files reviewed:
* neuralnet.cc/.h
- remove unused varaibles: data_layers_, parser_layers, loss_layers_
* trainer.cc/.h
* worker.cc/.h
- change shared_ptr to raw ptr for neuralnet object
all neuralnet object will be managed by trainer
trainer passes pointers to workers and releases them in destructor
* server.cc/.h
- remove thread_id field
- rename variables
nUpdate_ -> n_update_
nPendingSync_ -> n_pending_sync_
- fix a bug in HandleUpdate that using a *msg in a unknown state
* dirver.cc/.h
- rewrite headers in driver.h
- move template impl from driver.h to driver.cc
* singa.h
* main.cc
=> SINGA-21 Code review 5

include/utils/cluster_rt.h, src/utils/cluster_rt.cc, src/utils/tool.cc
JobManager read next available host from zookeeper,
and assign new jobs to that one, intead of always the first host
cluster.h / .cc
- add UpdateNode function in ZKService
- add GenerateHostList function in JobManager
- move ExtractCLusterConf from tool.cc to cluster.cc
=> SINGA-73 Refine the selection of available hosts

README.md
=> SINGA-68 Preparation for Release

include/singa/neuralnet/layer.h, include/singa/neuralnet/output_layer/csv.h, include/singa/neuralnet/output_layer/record.h, src/io/kvfile.cc, src/io/textfile_store.cc, src/neuralnet/output_layer/csv.cc, src/utils/cluster_rt.cc
Please see https://issues.apache.org/jira/browse/SINGA-90 and the individual commits for details.
=> Miscellaneous trivial bug fixes

examples/cifar10/job.conf
Add "momentum:0.9" to cifar10 example job.conf
=> (SINGA-96) Add Momentum to Cifar10 Example

examples/rbm/autoencoder.conf, examples/rbm/rbm3.conf, examples/rbm/rbm4.conf, include/singa/neuralnet/layer.h, include/singa/neuralnet/neuron_layer/rbm.h, src/neuralnet/neuron_layer/rbm.cc
* update Blob<float>& data(const Layer* from) function and Blob<float>* mutable_data(const Layer* from) in layer.h
* update data_, data() function and mutable_data() function in every layer.cc
=> SINGA-110 Add Layer member datavec_ and gradvec_

include/singa/neuralnet/connection_layer/concate.h, include/singa/neuralnet/connection_layer/slice.h, include/singa/neuralnet/connection_layer/split.h, include/singa/neuralnet/layer.h, src/neuralnet/connection_layer/concate.cc, src/neuralnet/connection_layer/slice.cc, src/neuralnet/connection_layer/split.cc, src/neuralnet/neuralnet.cc, src/proto/job.proto, src/test/test_connection_layers.cc
Added implementation for connection layers (slice, concate, split).
'make test' to run test cases.
=> SINGA-111 Add slice, concate and split layers

configure.ac, examples/cifar10/cudnn_hybrid.conf, examples/cifar10/hybrid.conf, include/singa/neuralnet/connection_layer.h, include/singa/neuralnet/layer.h, include/singa/neuralnet/neuralnet.h, include/singa/neuralnet/neuron_layer.h, include/singa/utils/graph.h, src/driver.cc, src/neuralnet/connection_layer/bridge.cc, src/neuralnet/connection_layer/concate.cc, src/neuralnet/connection_layer/slice.cc, src/neuralnet/connection_layer/split.cc, src/neuralnet/neuralnet.cc, src/neuralnet/neuron_layer/dummy.cc, src/proto/job.proto, src/test/test_connection_layers.cc, src/test/test_neuralnet.cc, src/utils/blob.cc, src/utils/common.cc, src/utils/graph.cc, src/worker.cc
NeuralNet can automatically add connection layers for distributed training.
Hence, the partition is transparent to users.
User just need to configure partition_dim field in NetProto:
partition_dim = 0 : data partition
partition_dim = 1 : model partition
User can also overwrite partition_dim for a specific layer in LayerProto.
This will result in hybrid partition.
=> SINGA-113 Model/Hybrid Partition Support

examples/alexnet/cudnn.conf, examples/char-rnn/job.conf, examples/cifar10/cudnn.conf, include/singa/neuralnet/neuron_layer.h, src/neuralnet/input_layer/onehot.cc, src/neuralnet/neuron_layer/gru.cc, src/proto/job.proto, src/test/test_gru_layer.cc, src/test/test_unrolling.cc
This is a new pull request for SINGA-120 - Implemented GRU and BPTT
=> SINGA-120 - Implemented GRU and BPTT: refined the code for readability

tool/python/README.md, tool/python/examples/cifar10_cnn.py, tool/python/examples/cifar10_cnn_cudnn.py, tool/python/singa/__init__.py, tool/python/singa/layer.py, tool/python/singa/model.py, tool/python/singa/utils/__init__.py
- Update README.md
- Update layer.py and model.py
. deal with non-square values for kernel, stride, pad
. users can specify Accuracy layer by 'show_acc=True'
- Update cifar10 examples
. set momentum to 0.9 to speed up convergence
=> SINGA-125 Improve Python Helper

examples/cifar10/cudnn_bm.conf, include/singa/neuralnet/neuron_layer.h, src/driver.cc, src/neuralnet/neuron_layer/bm.cc, src/neuralnet/neuron_layer/cudnn_bm.cc, src/neuralnet/neuron_layer/cudnn_convolution.cc, src/proto/job.proto
cudnn_convolution.cc: Add cudnn Vesrion Macro
Support cuDNN V4
=> SINGA-136 Support cuDNN v4

include/singa/utils/blob.h, include/singa/utils/math_addr.h, include/singa/utils/math_blob.h, src/test/test_math.cc
-------
add gtest for blob level functions
and bug fix in math_blob.h
=> SINGA-80 New Blob Level and Address Level Math Operation Interface

src/model/layer/cudnn_convolution.cc, test/singa/test_cudnn_convolution.cc
The following CUDNN functions are used:
cudnnFindConvolutionForwardAlgorithm,
cudnnFindConvolutionBackwardFilterAlgorithm,
cudnnFindConvolutionBackwardDataAlgorithm.
PS: test passed when setting prefer_ = "autotune".
=> SINGA-191 Add "autotune" for CudnnConvolution Layer

include/singa/core/tensor.h, src/core/tensor/math_kernel.cu, src/core/tensor/math_kernel.h, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h, test/singa/test_tensor_math.cc
Added error logs for tensor_math.h to specify which functions are not implemented.
=> SINGA-168 Implement Cpp Math functions API

src/model/layer/flatten.cc, src/model/layer/flatten.h, src/model/layer/prelu.cc, src/model/layer/prelu.h, src/proto/model.proto, test/singa/test_flatten.cc, test/singa/test_prelu.cc
Implement prelu and flatten layers and pass all tests.
=> SINGA-190 - Add prelu layer and flatten layer

include/singa/core/common.h, include/singa/core/device.h, include/singa/core/tensor.h, include/singa/model/layer.h, src/core/device/device.cc, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h, src/model/layer/cudnn_activation.cc, src/model/layer/cudnn_batchnorm.cc, src/model/layer/cudnn_convolution.cc, src/model/layer/cudnn_dropout.cc, src/model/layer/cudnn_lrn.cc, src/model/layer/cudnn_pooling.cc, src/model/layer/cudnn_softmax.cc, test/singa/test_cpp_cpu.cc, test/singa/test_tensor.cc
Rename Blob (blob) into Block (block).
Block represents a block of memory.
=> SINGA-196 Rename class Blob to Block

tool/mesos/singa_scheduler.cc
A bug was reported (https://issues.apache.org/jira/browse/SINGA-201) when
launching SINGA on Mesos in fully distributed mode.
The main cause was determined to be of ZeroMQ binding to the localhost. In fully
distributed mode, SINGA on each node should be passed a `-host` flag specifying
the public IP address of the local host.
The Mesos scheduler is modified accordingly:
1. When a Mesos slave starts connecting to the master, it passes `--hostname` flag specifying its public IP address
2. The scheduler now sends to each executor command of the form:
`singa -conf ./job.conf -singa_conf ./singa.conf -singa_job XX -host XX`
=> SINGA-201 Error when running Mesos

include/singa/io/reader.h, include/singa/io/writer.h, src/io/binfile_reader.cc, src/io/binfile_writer.cc, test/singa/test_binfile_rw.cc
Add base classes of IO(Reader and Writer)
Add KVFileReader and KVFileWriter for key-value files.
Pass a simple test for KVFile write and read.
Change CMakeLists under src and test folders.
=> SINGA-202 Add reader and writer for binary file

include/singa/io/reader.h, include/singa/io/writer.h, src/io/binfile_reader.cc, src/io/binfile_writer.cc, src/io/textfile_reader.cc, src/io/textfile_writer.cc, test/singa/test_textfile_rw.cc
Add TextFileReader and TextFileWriter for reading and writing csv files.
Pass a simple test for these two classes.
Fixed bugs in BinFileReader and BinFileWriter.
=> SINGA-211 Add TextFileReader and TextFileWriter for CSV files

include/singa/core/device.h, include/singa/core/tensor.h, include/singa/model/layer.h, src/core/device/device.cc, src/core/tensor/tensor.cc, src/python/swig/core_device.i, src/python/swig/core_tensor.i, src/python/swig/model_layer.i, src/python/swig/numpy.i, src/python/tensor.py, test/python/unittest_python.py
- Update core_tensor.i, tensor.py to take care of the following methods
. Random operations
. Axpy
. Mult
. Pow
. AddColumn, SubColumn, MultColumn, DivColumn, and xxxRow, etc.
. SumColumns, SumRows
- Revised model_layer.i, layer.h to take care of Shape (std::vector)
TODO: from_array() in python
=> SINGA-186 Create Python Tensor class

jenkins.sh
=> SINGA-214 add jenkins for CI support

include/singa/core/device.h, include/singa/core/memory.h, include/singa/model/optimizer.h, src/CMakeLists.txt, src/core/memory/memory.cc, src/model/optimizer/adagrad.cc, src/model/optimizer/optimizer.cc, src/python/device.py, src/python/initializer.py, src/python/layer.py, src/python/optimizer.py, src/python/setup.py.in, src/python/swig/model_layer.i, src/python/swig/model_optimizer.i, src/python/swig/singa.i, src/python/tensor.py, test/python/test_optimizer.py, test/python/test_tensor.py, test/singa/test_adagrad.cc, test/singa/test_platform.cc, test/singa/test_snapshot.cc
Add optimizer, regularizer and constraint python classes in src/python/optimizer.py.
to check this PR:
1. make singa with python enabled (ccmake or cmake -DUSE_PYTHON ..)
2. test c++ code, ./bin/test_singa
3. test python code,  cd {singa_root}/test/python/; 
python test_tensor.py
python test_optimzier.py
=> SINGA-199 Implement Python classes for SGD optimizers

README.md, src/io/textfile_reader.cc, test/singa/test_lmdb_rw.cc
Fixed a bug in TextFileReader;
Add codes to remove some files generated by LMDB test after testing.
Change URL to travis-ci in README.md.
=> SINGA-222 Fixed bugs in IO

.gitignore, include/singa/io/decoder.h, include/singa/io/encoder.h, src/io/textfile_decoder.cc, src/io/textfile_encoder.cc, test/singa/test_textfile_decoder.cc
Implement Encoder and Decoder for CSV file
Write test for it
=> SINGA-213 Implement Encoder and Decoder for CSV

doc/docs/cnn.md, doc/docs/installation.md
Draft documentation for installation and Cifar10 example
=> SINGA-225 Documentation for installation and Cifar10 example

src/model/layer/convolution.cc, src/model/layer/convolution.h, src/model/layer/pooling.cc, src/model/layer/pooling.h, test/singa/test_convolution.cc, test/singa/test_cudnn_convolution.cc, test/singa/test_pooling.cc
Implement cpp version of convolution layer and pooling layer.
Using some functions in previous version of Singa.
Pooling layer only supports max and average pooling(no stochastic).
Passed tests.
=> Singa-228 Add Cpp Version of Convolution and Pooling layer

src/model/layer/batchnorm.cc, src/model/layer/lrn.cc, test/singa/test_batchnorm.cc, test/singa/test_lrn.cc
layer.
Add batch normalization layer inplementation in C++ language.
=> SINGA-174 Add Batch Normalization layer and Local Response Nomalization

examples/mnist/README.md, examples/mnist/train.py, include/singa/core/tensor.h, src/core/tensor/math_kernel.cu, src/core/tensor/math_kernel.h, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h, src/python/singa/optimizer.py, src/python/singa/tensor.py, src/python/swig/core_tensor.i
Implement RBM python version on mnist data set
1. The model is following: http://www.cs.toronto.edu/~hinton/science.pdf
2. This model is implemented using python tensors
3. Users should first download mnist.pkl.gz
=> SINGA-238 RBM on mnist

examples/imagenet/ilsvrc12.h
Remove the fixed numbers of training and test images.
=> SINGA-241 Fix bugs in Imagenet example

src/CMakeLists.txt, test/CMakeLists.txt
Modify targets and related source codes
=> SINGA-242 Compile all source files into a single library.

src/python/singa/loss.py
Despite for some typos, it seems tensor does not support the operation like float * tensor. But tensor * float works.
=> Fix some typo and bug

python/CMakeLists.txt, python/rafiki/__init__.py, python/rafiki/agent.py, python/setup.py.in
- add rafiki python package
- firt version of rafiki agent module
=> SINGA-266 Add Rafiki python toolkits

src/model/layer/batchnorm.cc, test/singa/test_batchnorm.cc
Revise batchnorm test cases for spatial mode.
=> SINGA-267 Add spatial mode in batch normalization layer

python/singa/data.py, python/singa/tensor.py
Fix the error from tensor * float;
Fix the typo of 'delimeter' (should be 'delimiter') in data.py
=> SINGA-269 - Fix a bug from tensor multiplication and a typo

include/singa/core/tensor.h, include/singa/model/layer.h, python/singa/layer.py, python/singa/net.py, src/api/model_layer.i, src/core/tensor/tensor.cc, src/model/layer/concat.cc, src/model/layer/concat.h, src/model/layer/cudnn_rnn.cc, src/model/layer/slice.cc, src/model/layer/slice.h, src/model/layer/split.cc, test/python/test_layer.py, test/singa/test_concat.cc, test/singa/test_slice.cc
Add concatenate and slice layers in C++ and Python.
=> Singa 271-Add Concat and Slice layers

python/singa/image_tool.py
Add parameter "grayscale" to load method in image_tool.ImageTool.
=> SINGA-282 Add grayscale to load method in ImageTool class

python/setup.py.in, test/python/run.py, test/python/test_optimizer.py, tool/jenkins/README.md, tool/jenkins/docker/ubuntu14.04/Dockerfile, tool/jenkins/docker/ubuntu16.04/Dockerfile, tool/jenkins/jenkins_wheel.sh
update python unittest to genreate xml report;
update dockerfile to install unittest-xml-reporting;
update jenkins script to run python unittest;
add USE_MODULES for compiling protobuf and blas
skip cuda test if pysinga is not compiled with cuda
To test it with Jenkins, please read tool/Jenkins/README.md
To test it manually, please run the unit test by (after compile singa)
cd build/
./bin/test
cd ../test/python/
PYTHONPATH=../../build/python python run.py
=> SINGA-284 Add python unittest into Jenkins and link static libs into whl file

CMakeLists.txt, doc/en/docs/installation.md, python/rafiki/__init__.py, tool/debian/build.sh, tool/jenkins/README.md, tool/jenkins/jenkins_wheel.sh
To test this PR, just check if the whl files and debian files are usable:
http://www.comp.nus.edu.sg/~dbsystem/singa/assets/file/wheel/linux/latest/
http://www.comp.nus.edu.sg/~dbsystem/singa/assets/file/wheel/macosx/latest
http://www.comp.nus.edu.sg/~dbsystem/singa/assets/file/debian/latest/
after installation, enter python interpreter,
from singa import tensor
x=tensor.Tensor((2,3))
x.set_value(1)
y=2*x
tensor.to_numpy(y)
y
=> SINGA-293 and SINGA-292 for compiling SINGA on Mac OS X

python/singa/metric.py, python/singa/net.py, test/python/test_metric.py
=> SINGA-304 Add precision and recall for multilabel metrics

src/model/layer/batchnorm.cc, src/model/layer/concat.cc, src/model/layer/convolution.cc, src/model/layer/cudnn_activation.cc, src/model/layer/cudnn_batchnorm.cc, src/model/layer/cudnn_convolution.cc, src/model/layer/cudnn_dropout.cc, src/model/layer/cudnn_lrn.cc, src/model/layer/cudnn_pooling.cc, src/model/layer/cudnn_softmax.cc, src/model/layer/opencl_convolution.cc, src/model/layer/opencl_pooling.cc, src/model/layer/pooling.cc, src/model/layer/slice.cc
Update the layer settings and internal variables (e.g cudnn descriptors) if the input data's batchsize is changed from previous iteration.
TODO(wangwei) update the layer settings if the input sample shape changes.
=> SINGA-309 Update the layer setting/config dynamically

python/singa/optimizer.py, test/python/test_optimizer.py, tool/conda/build.sh, tool/conda/meta.yaml, tool/jenkins/README.md, tool/jenkins/docker/devel/centos6/Dockerfile, tool/jenkins/docker/devel/ubuntu14.04/Dockerfile
1. fix a bug in Adam optimizer about the step counting; add python unittest for Adam in test_optimzier.py
2. update conda build.sh/meta.yml for creating conda package on centos6
=> SINGA-311 and SINGA-310 

python/singa/image_tool.py
Added vertical flipping function (top - bottom flip) and method. Currently, only horizontal flipping (left - right flip) exists.
=> SINGA-321 Add vertical flip function and method in image_tool.py

python/singa/net.py
move the version outside if else statement
=> SINGA-327 Fix the bug of loading model saved in bin file

CMakeLists.txt
[Referencing](https://issues.apache.org/jira/browse/SINGA-330)
=> Singa-330 fix openblas building on i7 7700k

examples/imagenet/vgg/README.md, examples/imagenet/vgg/convert.py, examples/imagenet/vgg/model.py, examples/imagenet/vgg/serve.py
Add vgg models and the parameter conversion script.
The converted parameters are stored on S3.
The download links are providied in the readme file.
=> SINGA-328 - Add VGG models for ImageNet classification

examples/cifar10/train.py
Modify loading data part according to Moaz's comments so that it works for both Python 2 and 3.
=> SINGA-332 Fix the bug of loading data in train.py of cifar10

examples/cifar10/CMakeLists.txt, tool/jenkins/README.md, tool/jenkins/docker/devel/ubuntu/Dockerfile, tool/travis/build.sh, tool/travis/depends.sh
The documentation (README) of tool/jenkins is updated with details about using docker containers as the build agents.
A bug is fixed due to the change of alexnet.cc to cnn.cc in exmaple/cifar10
=> SINGA-345 Update Jenkins and fix bugs in compliation

python/singa/tensor.py, test/python/test_tensor.py
Fix the bug of dimension mismatch in test_einsum
=> SINGA-353 Fix the bug of test_einsum

doc/conf.py, doc/zh/community/issue-tracking.md, doc/zh/community/mail-lists.rst, doc/zh/community/source-repository.md, doc/zh/community/team-list.rst, doc/zh/develop/contribute-code.md, doc/zh/develop/how-contribute.md, doc/zh/develop/schedule.rst, doc/zh/docs.rst, doc/zh/downloads.md, doc/zh/index.rst
Wentong commit non-core part document translations. 
Document is able to build successfully on local machine.
Later on Ji Xin will commit core part document translations, and put them under **doc** folder.
=> SINGA-352 Complete SINGA documentation in Chinese version

doc/en/community/team-list.rst, doc/en/docs/install_win.rst
Also contains fixing name of Xin Ji in the team list.
=> SINGA-294 Add instructions to run unit tests on Windows

test/python/test_layer.py, test/python/test_loss.py, test/python/test_optimizer.py
I have implemented test cases as many as I can, and all test cases have been tested in the local environment.
The coding style and format follow the previous test cases.
=> SINGA-337 Add test cases for code

doc/en/docs/installation.md
=> update installation doc

examples/cifar10/train.py, python/singa/net.py
New codes have been tested locally and are able to run on the cifar10 dataset.
=> SINGA-368 Fix the bug in Cifar10 examples

examples/imagenet/densenet/README.md, examples/imagenet/densenet/convert.py, examples/imagenet/densenet/model.py, examples/imagenet/densenet/serve.py, examples/imagenet/googlenet/serve.py, examples/imagenet/inception/convert.py, examples/imagenet/inception/serve.py, examples/imagenet/resnet/convert.py, examples/imagenet/vgg/README.md, examples/imagenet/vgg/convert.py, examples/imagenet/vgg/serve.py
This pull request contains two commits:
1. Fix some bugs and rewrite some codes in the existing CNN models as much as I can, and I also ensure that no new bugs will be introduced in this commit.
2. Add DenseNet models, and all are able to run correctly in my local environment.
=> SINGA-363 Add DenseNet for Imagenet classification

examples/char-rnn/train.py, python/singa/net.py, python/singa/tensor.py
1.fix the error of "Tensor object has no attribute singa_tensor"
=> SINGA-369 fix the errors in examples

examples/imagenet/googlenet/serve.py, python/singa/net.py, python/singa/snapshot.py, python/singa/tensor.py
Fix the error of loading checkpoint files due to version mismatch.
=> SINGA-369 the errors of examples in testing

doc/en/releases/RELEASE_NOTES_1.2.0.md
This pull request move all ImageNet models into the "Model components" category.
=> SINGA-364 V1.2 Release Preparation

doc/en/releases/RELEASE_NOTES_1.2.0.md, doc/zh/docs/model_zoo/imagenet/densenet/README.md, doc/zh/docs/model_zoo/imagenet/inception/README.md, doc/zh/docs/model_zoo/imagenet/resnet/README.md, doc/zh/docs/model_zoo/imagenet/vgg/README.md, doc/zh/docs/model_zoo/index.rst, doc/zh/docs/model_zoo/mnist/README.md, examples/index.rst
Add missing documents of some SINGA examples, for both English and Chinese versions. Documents have been built successfully on local machine.
=> SINGA-352 Add Chinese documentations for SINGA examples

doc/en/downloads.md
=> SINGA-376 Update the download page

README.md, doc/README.md, doc/en/docs/notebook/README.md, doc/zh/docs/model_zoo/char-rnn/README.md, doc/zh/docs/model_zoo/cifar10/README.md, doc/zh/docs/model_zoo/imagenet/alexnet/README.md, doc/zh/docs/model_zoo/imagenet/densenet/README.md, doc/zh/docs/model_zoo/imagenet/googlenet/README.md, doc/zh/docs/model_zoo/imagenet/inception/README.md, doc/zh/docs/model_zoo/imagenet/resnet/README.md, doc/zh/docs/model_zoo/imagenet/vgg/README.md, doc/zh/docs/model_zoo/mnist/README.md, examples/caffe/README.md, examples/char-rnn/README.md, examples/cifar10/README.md, examples/imagenet/alexnet/README.md, examples/imagenet/densenet/README.md, examples/imagenet/googlenet/README.md, examples/imagenet/inception/README.md, examples/imagenet/resnet/README.md, examples/imagenet/vgg/README.md, examples/mnist/README.md, tool/conda/cpu/README.md, tool/conda/gpu/README.md, tool/conda/singa/README.md, tool/docker/README.md, tool/jenkins/README.md
=> Apache V2 License header added to readme

examples/autograd/mlp.py, examples/autograd/mnist_cnn.py, python/singa/autograd.py, python/singa/tensor.py, src/CMakeLists.txt, src/api/model_operation.i, src/api/singa.i, src/core/tensor/tensor.cc, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h, src/model/layer/convolution.cc, src/model/layer/convolution.h, src/model/layer/cudnn_convolution.cc, src/model/layer/cudnn_rnn.cc, src/model/operation/convolution.cc, src/model/operation/convolution.h, test/python/test_operation.py, tool/conda/singa/build.sh, tool/conda/singa/meta.yaml
Functions for convolution operations
=> SINGA-371 Implement functional operations in c++ for autograd

examples/autograd/mlp.py, examples/autograd/mnist_cnn.py, examples/cifar10/cnn-parallel.cc, examples/cifar10/vgg-parallel.cc, examples/imagenet/alexnet/alexnet.cc, examples/imagenet/alexnet/ilsvrc12.h, include/singa/core/tensor.h, python/singa/autograd.py, python/singa/tensor.py, src/api/core_tensor.i, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cuda.h, src/io/image_transformer.cc, src/model/layer/batchnorm.cc, src/model/layer/convolution.cc, src/model/layer/cudnn_batchnorm.cc, src/model/layer/cudnn_rnn.cc, src/model/layer/dense.cc, src/model/layer/flatten.cc, src/model/layer/lrn.cc, src/model/layer/opencl_convolution.cc, src/model/layer/rnn.cc, src/model/operation/convolution.cc, src/model/updater/local_updater.cc
(SINGA-380) Fix bugs from Reshape
(SINGA-381) Update the autograd API to yeild the gradients
=> Fix bugs and update APIs for reshape and transpose

doc/en/docs/installation.md
- update the installation command for installing SINGA with CUDA and cuDNN
=> SINGA-390 Update installation.md

examples/autograd/xceptionnet.py, python/singa/autograd.py, src/api/model_operation.i, src/model/operation/convolution.cc, src/model/operation/convolution.h, test/python/test_operation.py
The former Conv2d layer connot support Grouped Convolution, which make it difficult to realize some networks like inception net, xception net.
In this ticket, i will let Conv2d layer support Grouped convolution. and implement separable_conv2d which is the basic module in xception net by calling conv2d.
=> SINGA-383 Add Separable Convolution for autograd

examples/gan/download_mnist.py, examples/gan/lsgan.py, examples/gan/utils.py, examples/gan/vanilla.py
A preliminary version of GAN and LSGAN using SINGA APIs.
=> SINGA-344 Add a GAN example

examples/autograd/mlp.py, python/singa/autograd.py, test/python/test_operation.py
Change some APIs to Pytorch style.
Modified the corresponding test cases and example net.
=> SINGA-392 Update autograd API to Pytorch style

doc/en/docs/autograd_doc.md
the added doc give an overview of autograd mechanism, and then explain the codes of a simple example network implemented by autograd APIs.
=> SINGA-395 Add documentation for autograd APIs

python/singa/autograd.py
Correct the unsupportive function definition in line 1190 of "python/singa/autograd.py".
=> SINGA-408 Unsupportive function definition in python3

python/singa/net.py, src/io/snapshot.cc
=> SINGA-411 Local variable 'params' referenced before assignment

doc/en/community/source-repository.rst
Update source repository page with the new repo URL and instructions to use Gitbox.
=> SINGA-415 Moving SINGA to Gitbox

python/singa/autograd.py
…ad Layer class
- add these two functions for base layer and Conv2d Layer.
- did some test for these functions, the added functions work well.
- next step is to add these functions for other subclasses of autograd.Layer().
=> SINGA-410 Add two function, set_params() and get_params(), for Autograd Layer class

examples/mnist/train.py, python/singa/tensor.py
- fix unsupportive type 'long'
=> SINGA-418 Unsupportive type 'long' in python3

python/setup.py.in, tool/conda/singa/meta.yaml
Please uninstall the old singa and protobuf, and then install singa in a virtual env.
```
conda create -n singa
conda install -c nusdbsystem singa-cpu
```
=> Singa 422 Fix the error caused by protobuf version

tool/conda/docker/cuda10/Dockerfile, tool/conda/docker/cuda9/Dockerfile, tool/conda/singa/README.md, tool/conda/singa/build.sh, tool/conda/singa/meta.yaml, tool/jenkins/README.md
add CUDA to the script env in meta.yml and update the bash test for CUDA in build.sh
=> SINGA-432 Update depdent lib versions in conda-build config

RELEASE_NOTES, doc/en/releases/RELEASE_NOTES_2.0.0.md
=> SINGA-433 Preparation for V2.0 release

doc/en/index.rst
Added missing customers Foodlg and Medilot to the customers list in doc/en/index.rst
=> SINGA-454 fix

tool/conda/singa/conda_build_config.yaml, tool/conda/singa/meta.yaml
=> SINGA-409 Basic `singa-cpu` import throws error

tool/docker/README.md
https://issues.apache.org/jira/browse/SINGA-440?focusedCommentId=16814319&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16814319
=> SINGA-440 Update docker commands in docs

include/singa/core/tensor.h, src/core/tensor/tensor.cc, test/singa/test_tensor_math.cc
This is trying to fix `Tensor::GetValue()`, and make it consider `_stride`. More tests added for validation. ref. SINGA-462
=> transpose reshape fix ref. SINGA-462

src/core/tensor/tensor.cc, test/python/test_tensor.py, test/singa/test_tensor_math.cc
fixed reshape implementation, added more python unittest, fixed python tensor unittest ref.SINGA-462
=> SINGA-462 fix reshape and related

doc/en/docs/installation.md
Instructions for Centos7 SINGA installation added to the Installation.md file.
=> SINGA-466 Centos7 Installation instructions 

test/python/test_operation.py
Test Result:
root@26c9db193eb0:~/incubator-singa/build# python3 /root/incubator-singa/test/python/test_operation.py
....................................
Ran 36 tests in 1.010s
OK
=> SINGA-473 Autograd Trigonometry: Backward Test

python/singa/autograd.py, test/python/test_operation.py
SINGA-474 reshape operator for autograd and onnx operator
=> SINGA-474 reshape operator

python/singa/autograd.py, test/python/test_operation.py
SINGA-474 mul operator for autograd and ONNX operator
=> SINGA-474 mul operator

python/singa/autograd.py, test/python/test_operation.py
SINGA-474 transpose operator for onnx operator and autograd
=> SINGA-474 transpose operator

python/singa/autograd.py, test/python/test_operation.py
SINGA-474 Clip operator for autograd and ONNX
=> SINGA-474 Clip operator

python/singa/autograd.py, test/python/test_operation.py
Implement ONNX Operators following https://github.com/onnx/onnx/blob/master/docs/Operators.md
=> SINGA-474 greater operator

python/singa/autograd.py, test/python/test_operation.py
Implement ONNX Operators following https://github.com/onnx/onnx/blob/master/docs/Operators.md
=> SINGA-474 Mean operator

python/singa/autograd.py, test/python/test_operation.py
SINGA-474 sum operator for autograd and ONNX operator
=> SINGA-474 sum operator

python/singa/autograd.py, test/python/test_operation.py
fix conflict for operations test and autograd.
=> SINGA-474 fix origin conflict

python/singa/autograd.py
this is required to run the `autograd/resnet.py`
=> fixed operation add assertion for convolution

examples/autograd/resnet.py, examples/autograd/resnet_dist.py, include/singa/core/device.h, python/singa/autograd.py, python/singa/opt.py, src/api/core_device.i, src/core/device/cuda_gpu.cc, src/core/tensor/tensor_math_cuda.h
I have fused the small operations of momentum SGD so as to increase GPU computation efficiency and decrease latency. Moreover, I have added the Sync() function for better time profiling in resnet.py (wait for the previous cuda operations to be finished before start calculating the time).
1. This is the new result after improving the momentum SGD:
```
ubuntu@ip-172-31-39-137:~/incubator-singa/examples/autograd$ python3 mnist_cnn.py
Training loss = 583.052124, training accuracy = 0.793690
Evaluation accuracy = 0.943409, Elapsed Time = 4.191409s
Training loss = 229.894424, training accuracy = 0.923609
Evaluation accuracy = 0.961438, Elapsed Time = 4.170332s
Training loss = 168.670303, training accuracy = 0.943937
Evaluation accuracy = …
```
=> SINGA-490 Optimize performance of stochastic gradient descent (SGD)

README.md, include/singa/core/tensor.h, include/singa/io/decoder.h, include/singa/io/transformer.h, python/singa/sonnx.py, src/model/layer/activation.h, src/model/layer/batchnorm.h, src/model/layer/flatten.h, src/model/layer/prelu.h, src/model/layer/split.h, src/model/operation/batchnorm.h
Adding code analysis badges to README.
=> SINGA-484 Code analysis with LGTM

examples/autograd/resnet.py, examples/autograd/xceptionnet.py, examples/cifar10/train.py, examples/imagenet/densenet/model.py, examples/imagenet/densenet/serve.py, examples/imagenet/googlenet/serve.py, examples/imagenet/inception/README.md, examples/imagenet/inception/inception_v3.py, examples/imagenet/inception/inception_v4.py, examples/imagenet/inception/serve.py, examples/imagenet/resnet/serve.py, examples/imagenet/vgg/serve.py, python/singa/autograd.py, python/singa/sonnx.py, tool/opencl/clsrc_to_str.py
Only Python code is cleaned at this time that is likely to remove around hundred alerts in python code.
Since there are lots of changes in the folders examples/imagenet/inception and examples/imagenet/googlenet, I have run those code again including four parts:
PART (I) examples/imagenet/googlenet/serve.py
PART (II) examples/imagenet/inception/inception_v3.py
PART (III) examples/imagenet/inception/inception_v4.py
PART (IV) Python Unit Test (test_operation.py)
Two test photos from the imagenet dataset are used for testing in PART (I), (II), (III) 
image1.JPEG
image2.JPEG
The results are okay as expected.
PART (I) examples/imagenet/googlenet/serve.py
```
ubuntu@ip-172-31-39-12:~/incubator-singa/examples/imagenet/googlenet$ python3 serve.py &
runing with gpu
* Serving Flask app …
```
=> SINGA-491 Python Code Cleaning

doc/en/index.rst
-add Food(lg) news in the SINGA homepage
=> SINGA-492 add Food(lg) news in the documentation

python/rafiki/agent.py, tool/cpplint.py
This is to clean some remaining LGTM Python code alerts that I am capable to clean. This is the last PR for my current code cleaning, because after this PR I think the current code is clean enough. Meanwhile, in the future I can still help to clean when there are new LGTM alerts.
For some false positive alarms in LGTM, I have submitted the query in semmle/ql that might help them to debug their system:
https://github.com/Semmle/ql/issues
`https://github.com/Semmle/ql/issues/2101`
`https://github.com/Semmle/ql/issues/2071`
=> SINGA-491 Remaining LGTM Python Code Cleaning

include/singa/core/tensor.h, src/api/core_tensor.i, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h, test/python/test_api.py, test/singa/test_tensor_math.cc
splitting https://github.com/apache/incubator-singa/pull/538 into two parts, this PR is for softmax with axis, which is compatible to onnx api
Ref. SINGA-476
=> SINGA-476 added softmax with axis

doc/build.sh
Add an webpage build path in build.sh
=> SINGA-493 Add an additional build path

doc/en/develop/how-to-release.rst, doc/en/downloads.md, doc/zh/downloads.md
Updated the download page to add "incubating" after the names of the previous
releases in the downloads page.
=> SINGA-493 Update downloads.md 

examples/autograd/cifar10_multiprocess.py, examples/autograd/mnist_cnn.py, examples/autograd/resnet_cifar10.py, python/singa/opt.py
In this PR, there are two things added:
1. An experimental feature for distributed training is added in opt.py, which is referred as
"Asynchronous training algorithm with partial parameters synchronization"
The algorithm is very simple but communicational effective. The steps are:
(I) Every GPU do the local training and update as normal.
(II) At each iteration a partition of the full parameters set is synchronized by all-reduce, where the size of partition determined by the tensor fusion threshold
2. The example codes using CIFAR-10 dataset on Resnet-50 to test the above algorithm (i.e. cifar10_multiprocess.py), as well as doing single GPU training (i.e. resnet_cifar10.py).
The following is the log using AWS g4dn.12xlarge (i.e. 4 * T4 GPUs). It can train to 99.2% training accuracy or …
=> SINGA-487 Asynchronous Training with Partial Parameters Synchronization

src/core/tensor/tensor_math_cuda.h, test/python/test_api.py
fixed div and pow operator when broadcasting
broadcast tests covered add, sub, mul, pow, div on transpose cases
ref. https://github.com/apache/singa/pull/545
=> fixed broadcast div pow

python/singa/autograd.py, python/singa/sonnx.py, test/python/test_onnx.py, test/python/test_onnx_backend.py, test/python/test_operation.py
Add GlobalAVGPool operator for autograd and onnx
=> SINGA-503 Add GlobalAVGPool operator for autograd and onnx

include/singa/io/communicator.h, src/io/communicator.cc
I suggest format the code in distributed module first, so that the changes in future PR can be tracked more easily.
=> Clang format for distributed module

python/singa/autograd.py, python/singa/sonnx.py, test/python/test_onnx_backend.py
* We can support the input of clip like [x, min, max], [x, min], [x], cannot support like [x, max]
* Add shape check of auto_pad for conv2d of onnx
=> fix bugs for some cases of onnx

src/api/model_operation.i
@XJDKC Thanks RULIN for finding out the bug during the cmake operation
=> Fix a bug: change #IF USE_CUDNN to #IF USE_DNNL

.github/workflows/rat.yaml, .pylintrc, java/pom.xml, rat-excludes, test/python/test_memoryPool.py, tool/rat.sh
This PR is an example for using Github Actions. 
The RAT test will pass after the apache:dev is merged with apache:master.
=> SINGA-508 Add Apache RAT licence check with Github Actions

python/singa/autograd.py
@nudles , I've checked the whole file again and fixed these problems, please check.
=> add function comments for autograd

include/singa/core/device.h, include/singa/core/scheduler.h, python/singa/module.py, src/api/core_device.i, src/core/scheduler/scheduler.cc, test/python/test_module.py, test/singa/test_scheduler.cc
Add some unit test cases for computational graph.
Includes:
* [test_module.py](https://github.com/XJDKC/singa/tree/graph_ut/test/python/test_module.py)
* [test_scheduler.py](https://github.com/XJDKC/singa/tree/graph_ut/test/singa/test_scheduler.cc)
=> Unit test cases for computational graph.

tool/docker/devel/ubuntu/cuda9/Dockerfile
a small bug fix in cuda 9 dockerfile
=> bug fix in cuda 9 dockerfile: change cuda10 to cuda 9 in nccl

examples/mnist/train.py
=> fix_mnist_example

test/python/test_dist.py
disable test if USE_DIST=FALSE
=> Fix test_dist.py

python/singa/module.py, test/singa/test_scheduler.cc
* Fix compile error caused by namespace
* Fix failed test cases
=> Fix bugs of scheduler unit test

examples/cnn/data/cifar10.py, examples/cnn/data/cifar100.py, examples/cnn/data/mnist.py, examples/cnn/train.py, examples/mlp/module.py
Since the path of cnn/data/mlp.py is changed to mlp/module.py, I have adjusted the path for importing mlp in train.py
=> fix path for mlp in train.py

src/api/model_operation.i, src/core/scheduler/scheduler.cc, test/python/cuda_helper.py, test/python/test_dist.py, test/python/test_module.py, test/python/test_onnx_backend.py, test/python/test_operation.py
just one line change in cuda_helper.py
```
root@71ac539cda77:~/dcsysh/singa/test/python# python3 test_api.py
......................
Ran 22 tests in 0.164s
OK
root@71ac539cda77:~/dcsysh/singa/test/python# python3 test_operation.py
..............................................................................................................................................................................
Ran 174 tests in 1.255s
OK
```
=> Fix cuda_helper.py and test cases

examples/onnx/arcface.py, examples/onnx/fer_emotion.py, examples/onnx/mnist.py, examples/onnx/mobilenet.py, examples/onnx/resnet18.py, examples/onnx/tiny_yolov2.py, examples/onnx/utils.py, examples/onnx/vgg16.py, python/singa/autograd.py, test/python/test_onnx_backend.py, test/python/test_operation.py
- add the function MeanSquareError back and fix the bug at the previous test case,
- fix code format of several files
=> Add mean square error back and fix test case

test/python/test_api.py, tool/conda/singa/meta.yaml
See the travis CI response of Macos
=> Macos conda package: match conda protobuf version to conda onnx version

RELEASE_NOTES, examples/rnn/README.md, examples/rnn/train.py, python/singa/autograd.py, tool/release/release.py
Note the placeholder tensors for the input data and labels
should be reused after the first iteration.
TODO test model.graph(True, False).
=> Update rnn example to use the Module API from v3.0

examples/onnx/training/model.json, examples/onnx/training/train.py, python/singa/sonnx.py, test/python/test_onnx_backend.py
- fix soonx test cases
- change the default training example to resnet
=> fix soonx test cases

python/singa/autograd.py, test/python/test_operation.py
=> add cossim operator

examples/cnn/benchmark.py, include/singa/core/common.h, include/singa/core/scheduler.h, include/singa/io/communicator.h, src/core/device/cuda_gpu.cc, src/core/scheduler/scheduler.cc, src/io/communicator.cc
(Updated on 2 June 2020)
I am working on the distributed training time profiling
Done:
1. Moved the cuda streams from `Communicator` to `Context`
2. Time Profiling for Commmunicator buffered operations
3. Break down some communication kernel using different streams to exclude the waiting time in profiling
4. Added verbosity level 3 for showing distributed operators only
5. Rewrote the backward time (verbosity=1) to adapt for distributed training
Current Result tested in panda 18 (eight GPUs) is:
```
root@e8a757397ca3:~/dcsysh/singa/examples/cnn# mpiexec -np 8 python3 benchmark.py --dist --verbosity 3
100%|##########| 100/100 [00:18<00:00,  5.51it/s]Throughput = 1389.5021244306654 per second
TotalTime=18.42386531829834
Total=0.1842386531829834
Time Profiling:
OP_ID242. …
```
=> SINGA-510 Distributed Training Time Profiling

examples/onnx/shufflenetv1.py
Added ONNX example for Shufflenetv1. From onnx model zoo example https://github.com/onnx/models/raw/master/vision/classification/shufflenet/model/shufflenet-9.tar.gz
=> Shufflenetv1

examples/onnx/densenet121.py
Implement Densenet121 using ModelZoo from ONNX
=> Implement densenet121 from ONNX

test/python/test_onnx_backend.py
Fix onnx backend cuda cases when there is not a gpu device.
=> fix onnx backend cuda cases

include/singa/core/tensor.h, python/singa/autograd.py, python/singa/tensor.py, src/api/core_tensor.i, src/core/tensor/math_kernel.cu, src/core/tensor/math_kernel.h, src/core/tensor/tensor.cc, src/core/tensor/tensor_math.h, src/core/tensor/tensor_math_cpp.h, src/core/tensor/tensor_math_cuda.h, test/python/test_tensor.py, test/singa/test_tensor_math.cc
Currently we use `>= && <=` to substitute `==`
So in this PR, we add the equal operator directly
=> Add Equal Operator and its Computation Kernals

include/singa/core/device.h, include/singa/core/scheduler.h, python/singa/device.py, python/singa/sonnx.py, src/api/core_device.i, src/core/device/cuda_gpu.cc, src/core/device/device.cc, src/core/device/platform.cc, src/core/scheduler/scheduler.cc, test/python/cuda_helper.py, test/python/test_dist.py
It fixes the problem that the original function could occupy multiple GPUs memory
=> Fix create_cuda_gpu

examples/qabot/train.py, examples/rnn/imdb_data.py, examples/rnn/imdb_model.py, examples/rnn/imdb_train.py, java/pom.xml, python/singa/autograd.py, python/singa/tensor.py, src/core/tensor/tensor_math_cpp.h, test/python/test_opt.py
This PR can fix the cpp test case in #761  
```
root@71ac539cda77:~/dcsysh/singa/build/bin# ./test_singa
Running main() from gtest_main.cc
[==========] Running 159 tests from 35 test cases.
[----------] Global test environment set-up.
[----------] 1 test from Accuracy
[ RUN      ] Accuracy.Compute
[       OK ] Accuracy.Compute (0 ms)
[----------] 1 test from Accuracy (0 ms total)
[----------] 3 tests from Activation
[ RUN      ] Activation.Setup
[       OK ] Activation.Setup (0 ms)
[ RUN      ] Activation.Forward
[       OK ] Activation.Forward (0 ms)
[ RUN      ] Activation.Backward
[       OK ] Activation.Backward (0 ms)
[----------] 3 tests from Activation (0 ms total)
[----------] 1 test from AdaGrad
[ RUN      ] AdaGrad.ApplyCPU
[       OK ] AdaGrad.ApplyCPU (0 ms)
[----------] 1 …
```
=> Fix python and c++ test cases

python/singa/device.py, test/python/test_onnx.py, test/python/test_tensor.py
Continue to fix the remaining python test cases
=> Fix python test cases

examples/onnx/gpt2/gpt2.py, examples/onnx/gpt2/requirements.txt, python/singa/autograd.py, python/singa/sonnx.py, test/python/test_operation.py
- The output is correct now,
- But cannot generate more words, 
- Mostly it is an issue of onnx model, not sonnx, still checking
=> Add onnx gpt2 model

.github/workflows/cpp.yaml, .github/workflows/macOS.yaml, README.md
This is the first build with Github Actions which can be used to replace Travis CI.
=> C++ build with Github Actions

include/singa/core/tensor.h, src/core/tensor/math_kernel.cu, src/core/tensor/math_kernel.h, src/core/tensor/tensor.cc, src/core/tensor/tensor_math_cuda.h, test/python/test_tensor.py
Added broadcasted() flag for tensor
Added broadcast to mult
Refactored gpu traverse unary
=> Broadcast for Mult

src/model/layer/activation.cc
=> Updated activation.cc

python/singa/autograd.py
=> fix_expand_operator

examples/cnn/model/alexnet.py, examples/cnn/model/cnn.py, examples/cnn/model/resnet.py, examples/cnn/model/xceptionnet.py, examples/cnn/train_cnn.py, examples/cnn/train_mpi.py, examples/cnn/train_multiprocess.py, examples/mlp/model.py, include/singa/io/communicator.h, python/singa/opt.py, src/core/tensor/tensor.cc, src/io/communicator.cc
In the dev branch, since the fp16 was added in the opt module by Shicong, I should update the distributed optimizer accordingly to support the change
=> SINGA-511 Compatibility of fp16 to distributed optimizer

examples/onnx/densenet121.py, examples/onnx/shufflenetv1.py, examples/onnx/shufflenetv2.py, examples/onnx/squeezenet.py, examples/onnx/vgg19.py
some examples were written by interns, and they were using the old API format, fix and update these examples to use new APIs.
=> fix some onnx examples to use new API

examples/onnx/densenet121.py, examples/onnx/shufflenetv1.py, examples/onnx/squeezenet.py, python/singa/utils.py
As title, recent PRs generated some LSTM alerts to be fixed
=> Fix some new LSTM alerts

examples/largedataset_cnn/README.md, examples/largedataset_cnn/process_data.py, examples/largedataset_cnn/train_largedata.py, examples/largedataset_cnn/train_mpi.py
This PR includes a new example folder of training CNN by reading a large image dataset from the filesystem
=> An example Large dataset CNN

examples/largedataset_cnn/process_data.py, examples/largedataset_cnn/train_largedata.py
=> Fix LSTM minor alert and bug

.github/workflows/conda.yaml, python/singa/sonnx.py
As title, the conda-build version in dev branch does not work for the reason in #829 , so this PR fix the issue
=> Also fix the conda-build in dev branch

examples/largedataset_cnn/README.md
Add information concerning the dataset format of the new CNN example
=> Update README.md for the new CNN example

examples/mlp/model.py, examples/mlp/native.py
=> Update the MLP example

examples/cnn/autograd/mnist_cnn.py, examples/cnn/autograd/mnist_multiprocess.py, examples/cnn/autograd/resnet_cifar10.py, examples/cnn/autograd/sparsification_mnist.py
=> Update cnn autograd

examples/cifar_distributed_cnn/README.md, examples/cifar_distributed_cnn/train_mpi.py
add distributed training for cifar-10 using resnet
=> add distributed training for cifar-10 using resnet

examples/cifar_distributed_cnn/train_multiprocess.py
add multiprocess distributed training for cifar-10
=> Add multiprocess distributed training for cifar-10

examples/cifar_distributed_cnn/run-rtx.sh
script for distributed training of cifar-10
=> script for distributed training of cifar-10

examples/cifar_distributed_cnn/data/cifar100.py, examples/cifar_distributed_cnn/model/xceptionnet.py
create folders for autograd and data modules for cifar_distributed_cnn
=> create folders for data modules for cifar_distributed_cnn

examples/cifar_distributed_cnn/autograd/xceptionnet.py
add autograd for xceptionnet in cifar_distributed_cnn
=> add autograd for xceptionnet in cifar_distributed_cnn

examples/cifar_distributed_cnn/autograd/mnist_cnn.py, examples/cifar_distributed_cnn/autograd/mnist_dist.py, examples/cifar_distributed_cnn/autograd/mnist_multiprocess.py
autograd for mnist in cifar_distributed_cnn
=> autograd for mnist in cifar_distributed_cnn

examples/cifar_distributed_cnn/benchmark.py
add benchmark.py for cifar_distributed_cnn
=> add benchmark.py for cifar_distributed_cnn

examples/cifar_distributed_cnn/train_cnn.py
train script for cifar 10 distributed training
=> train script for cifar 10 distributed training

examples/cifar_distributed_cnn/run-rtx.sh
remove run-rtx.sh from cifar_distributed_cnn folder
=> remove run-rtx.sh from cifar_distributed_cnn folder

examples/largedataset_cnn/process_data.py
include the Apache license header for process_data.py
=> include the Apache license header for process_data.py

examples/cifar_distributed_cnn/autograd/resnet_dist.py, examples/largedataset_cnn/process_data.py
1. add resnet_dist autograd model in cifar_distributed_cnn example
2. update main function in largedataset_cnn/process_data.py
=> Add resnet_dist autograd model in cifar_distributed_cnn example

examples/cifar_distributed_cnn/autograd/resnet_cifar10.py
Add resnet_cifar10 to cifar_distributed_cnn/autograd
=> Add resnet_cifar10 to cifar_distributed_cnn/autograd

examples/cifar_distributed_cnn/run-rtx.sh
=> update running script for cnn

examples/demos/Classification/BloodMnist/ClassDemo.py
add training script for bloodmnist
=> add training script for bloodmnist

examples/demos/Classification/BloodMnist/ClassDemo.py
add Apache license header for ClassDemo.py
=> add Apache license header for ClassDemo.py

examples/demos/Classification/BloodMnist/transforms.py
update comments for class Compose
=> update comments for class Compose

examples/demos/Classification/BloodMnist/ClassDemo.py
update optimizer for bloodmnist.
=> update optimizer for bloodmnist

examples/singa_easy/README.md
create example folder for medical image analysis application
=> Create example folder for medical image analysis application

examples/singa_easy/singa_easy/modules/explanations/lime/lime.py
update the lime interpretation module
=> update the lime interpretation module

examples/singa_easy/singa_easy/modules/explanations/lime/lime.py
add Apache license header for lime.py
=> add Apache license header for lime.py

examples/demos/Classification/BloodMnist/transforms.py
update comments for ToTensor class
=> update comments for ToTensor class

examples/demos/Classification/BloodMnist/ClassDemo.py
update training script for bloodmnist
=> update training script for bloodmnist

examples/singa_easy/scripts/stop.sh
Update stop script by adding apache licence header
=> Update stop script by adding apache licence header

examples/demos/Classification/BloodMnist/Readme.md
=> update readme for bloodmnist

examples/demos/Classification/BloodMnist/ClassDemo.py
update the main function for bloodmnist
=> update the main function for bloodmnist

examples/largedataset_cnn/model/alexnet.py
add Alex net model for largedataset_cnn
=> add Alex net model for largedataset_cnn

examples/largedataset_cnn/model/resnet.py
add resent implementation for largedataset
=> add resent implementation for largedataset

examples/largedataset_cnn/model/cnn.py
add cnn implementations for large dataset example
=> add cnn implementations for large dataset example

examples/demos/Classification/BloodMnist/Readme.md, examples/singa_easy/README.md
1. Add apache license headers to BloodMnis/README
2. Add apache license headers to SingaEasy/README
=> Add apache license headers to readme

RELEASE_NOTES
1. add release_notes for v3.3.0
=> Add release_notes for v3.3.0

setup.py, tool/conda/singa/conda_build_config.yaml, tool/conda/singa/meta.yaml, tool/docker/devel/centos6/cuda10/Dockerfile.manylinux2014
update conda and docker files for v3.3.0
=> update conda and docker files for v3.3.0

tool/docker/runtime/cpu/Dockerfile, tool/docker/runtime/gpu/Dockerfile
update the runtime Dockerfile for v3.3
=> update the runtime Dockerfile for v3.3

examples/demos/Classification/BloodMnist/ClassDemo.py
Update inline comments for prepreocessing and data loading
=> Update inline comments for prepreocessing and data loading

examples/demos/Classification/BloodMnist/transforms.py
=> Update PIL image conversion

examples/demos/Classification/BloodMnist/ClassDemo.py
Update inline comments for model configuration.
=> Update inline comments for model configuration

examples/singa_easy/singa_easy/modules/explanations/__init__.py
add init file for explanations
=> add init file for explanations

examples/demos/Classification/BloodMnist/ClassDemo.py
1. Update inline comments for iterative training
=> Update  iterative training

examples/singa_easy/singa_easy/modules/explanations/__init__.py
1. Add Apache header for explanation init file
=> Add Apache header for explanation init file

examples/singa_easy/singa_easy/__init__.py
Add init file for medical image image analysis application
=> Add init file for medical image image analysis application

examples/singa_easy/singa_easy/__init__.py
Add Apache license header for medical image application init file.
=> Add Apache license header for medical image application init file.

examples/cifar_distributed_cnn/autograd/cifar10_multiprocess.py
Configure number of GPUs to be used
=> Configure number of GPUs to be used

examples/cnn/autograd/cifar10_multiprocess.py
1. Configure gpu numbers for the example cnn model
=> Configure gpu numbers for the example cnn model

examples/cifar_distributed_cnn/data/download_mnist.py
1. Update the mnist dataset downloading
=> Update the mnist dataset downloading

examples/cnn/autograd/xceptionnet.py
update Relu layer for xceptionnet in cnn example
=> update Relu layer for xceptionnet in cnn example

examples/cifar_distributed_cnn/autograd/resnet_cifar10.py
Update inline comments for cifar_distributed_cnn resnet_cifar10
=> Update inline comments for cifar_distributed_cnn resnet_cifar10

examples/cifar_distributed_cnn/autograd/xceptionnet.py
update Relu layer for xceptionnet in cifar_distributed_cnn example
=> update Relu layer for xceptionnet in cifar_distributed_cnn example

examples/singa_easy/singa_easy/modules/__init__.py
Add init file for medical image application modules
=> Add init file for medical image application modules

examples/singa_easy/singa_easy/modules/__init__.py
Add Apache license header for medical image application init file
=> Add Apache license header for medical image application init file

examples/cnn/run.sh
Add running script for cnn example
=> Add running script for cnn example

examples/cifar_distributed_cnn/run-rtx.sh
Add mlp running script for cifar_distributed_cnn example
=> Add mlp running script for cifar_distributed_cnn example

examples/cnn/run.sh
Add licence header for cnn run script
=> Add licence header for CNN run script

examples/cnn/run.sh
Add running script for cnn cifar datasets.
=> Add running script for cnn cifar datasets

examples/cnn/train_cnn.py
Increase max epoch for cnn example for better convergence
=> Increase max epoch for cnn example for better convergence

examples/cnn/train_cnn.py
print intermediate mini-batch information
=> print intermediate mini-batch information

examples/cnn/data/mnist.py
Save the downloaded mnist dataset to specific local directories
=> Save the downloaded mnist dataset to specific local directories

examples/cifar_distributed_cnn/data/cifar10.py
Pass in the data path for loading training data
=> Pass in the data path for loading training data

examples/cifar_distributed_cnn/train_cnn.py
Print intermediate results for cifar_distributed_cnn example
=> Print intermediate results for cifar_distributed_cnn example

examples/cnn/data/download_cifar10.py, examples/cnn/data/download_cifar100.py
Download cifar10 and cifar100 to local directories
=> Download cifar10 and cifar100 to local directories

examples/largedataset_cnn/autograd/cifar10_multiprocess.py
add cifar 10 multi process for large dataset cnn
=> add cifar 10 multi process for large dataset cnn

examples/largedataset_cnn/autograd/mnist_cnn.py
=> add mnist cnn model

examples/largedataset_cnn/autograd/mnist_dist.py
1. autograd for mnist dist in largedataset_cnn
=> Autograd for mnist dist in largedataset_cnn

examples/largedataset_cnn/autograd/mnist_multiprocess.py
1. multi process for mnist dataset
=> multi process for mnist dataset

examples/largedataset_cnn/autograd/resnet_cifar10.py
add resnet of cifar-10 dataset for largedataset_cnn example
=> add resnet of cifar-10 dataset for largedataset_cnn example

examples/largedataset_cnn/autograd/resnet_dist.py
=> add resnet dist version

examples/largedataset_cnn/autograd/xceptionnet.py
add xceptionnet for largedataset_cnn example
=> add xceptionnet for largedataset_cnn example

examples/largedataset_cnn/autograd/sparsification_mnist.py
add sparsification implementation for mnist
=> add sparsification implementation for mnist

examples/cifar_distributed_cnn/run-rtx.sh
Add running scripts for cifar100 dataset in cifar_distributed_cnn
=> Add running scripts for cifar100 dataset in cifar_distributed_cnn

examples/cifar_distributed_cnn/run-rtx.sh, examples/cnn/run.sh
Add scripts for alexnet model and mnist dataset in cnn examples
=> Add scripts for alexnet model and mnist dataset in cnn examples

RELEASE_NOTES
=> Release Notes for v4.0.0

examples/cifar_distributed_cnn/run-rtx.sh
Add scripts for the MNIST dataset using MLP and Alexnet models
=> Add scripts for the MNIST dataset using MLP and Alexnet models

NOTICE
Update the NOTICE file for images
=> Update the NOTICE file for images

examples/mlp_postgresql/README.md
mlp model examples on top of postgresql
=> mlp model examples on top of postgresql

examples/malaria_cnn/README.md
Readme for malaria prediction with CNN model
=> readme for malaria prediction with cnn model

examples/malaria_cnn/run.sh
Add the shell command file to run the codes.
=> add shell command file to run the codes

examples/model_selection_psql/README.md
Init the model selection examples, and add README.md
=> Init the model selection examples, and add README.md

examples/armnet/README.md
examples/armnet contains all the implementations and results of the Adaptive Relation Modeling technique for Structured Data.
> [ARM-Net: Adaptive Relation Modeling Network for Structured Data](https://dl.acm.org/doi/10.1145/3448016.3457321)
=> Init armnet examples, add README.md

examples/malaria_cnn/model/cnn.py
This pull request adds cnn model for malaria detection.
=> add cnn model for malaria detection

examples/malaria_cnn/model/mlp.py
add mlp model for malaria detection
=> add mlp model for malaria detection

examples/model_selection_psql/ms_mlp/train_mlp.py
Add SGD optimizer for model selection
=> Add SGD optimizer for model selection

examples/model_selection_psql/ms_mlp/train_mlp.py
Add implementation for get and set states
=> Add get and set states

examples/model_selection_psql/msmlp/model.py
Add implementation for mlp models in model selection
=> Add implementation for mlp models in model selection

examples/model_selection_psql/msmlp/model.py
Add implementation for sum error loss for model selection
=> Add implementation for sum error loss for model selection

examples/model_selection_psql/msmlp/model.py
Add the backward implementation for sum error loss
=> Add the backward implementation for sum error loss

examples/model_selection_psql/msmlp/model.py
Add the SumErrorLayer implementation
=> Add the SumErrorLayer implementation

examples/model_selection_psql/ms_model_mlp/model.py
Create the ms_model_mlp folder for dynamic model creation
=> Create the ms_model_mlp folder for dynamic model creation

examples/model_selection_psql/msmlp/native.py
Add the autograd implementation for msmlp
=> Add the autograd implementation for msmlp

examples/model_selection_psql/ms_model_mlp/model.py
Add train one batch function for the dynamic model
=> Add train one batch function for the dynamic model

examples/model_selection_psql/ms_model_mlp/native.py
Add autograd implementation for dynamic model creation
=> Add autograd implementation for dynamic model creation

examples/model_selection_psql/ms_mlp/train_mlp.py
Debug the training process for training free model evaluation metric
=> Debug the training process for training free model evaluation metric

examples/model_selection_psql/ms_mlp/train_mlp.py, examples/model_selection_psql/msmlp/model.py
The training process for mlp models with varying layer sizes
=> Training process for mlp models with varying layer sizes

examples/model_selection_psql/ms_mlp/train_multiprocess.py
Training script for model selection
=> Training script for model selection

examples/model_selection_psql/ms_mlp/train_mlp.py
Optimize model training in multi-layer perceptron.
=> Update the training file for dynamic models

doap/doap_SINGA.rdf
Add the doap file to the project
=> Add the doap file to the project

examples/model_selection_psql/ms_mlp/train_cnn.py
Add the training script for CNN models
=> Add the training script for CNN models

examples/model_selection_psql/ms_mlp/train_mpi.py
Add the training script for models using MPI
=> Add the training script for models using MPI

examples/model_selection_psql/pkg_model_code/model.py
Add the ModelMeta for dynamic models
=> Add the ModelMeta for dynamic models

examples/model_selection_psql/pkg_model_code/model.py
=> Update the ModelMeta class

examples/model_selection_psql/ms_mlp/run.sh
Add the running script for model selection
=> Add the running script for model selection

examples/model_selection_psql/ms_mlp/train_ms_model.py
Add the training script for model selection
=> Add the training script for model selection

examples/model_selection_psql/ms_mlp/train_ms_model.py
Add data processing functions for model selection
=> Add data processing functions for model selection

examples/model_selection_psql/ms_mlp/train_ms_model.py
Add the optimizer for model selection
=> Add the optimizer for model selection

examples/model_selection_psql/ms_mlp/train_ms_model.py
Add the implementation of a single optimization step for model selection
=> Add the implementation of a single optimization step for model selection

doap/doap_SINGA.rdf, java/pom.xml
=> fix the rat check files

setup.py, tool/docker/devel/centos6/cuda10/Dockerfile.manylinux_2_28_x86_64, tool/wheel.sh
Update python versions of wheel files
=> Update python versions of wheel files

examples/hfl/client.py, examples/hfl/server.py
This pull request adds the implementation of server and client for the horizontal federated learning example.
=> Add implementation for server and client for the hfl example

examples/hfl/bank.py, examples/hfl/mlp.py
This pull request adds the implementation of model and data processing for the horizontal federated learning example.
=> Add implementation for model and data processing for the hfl example

examples/hfl/config/.gitignore, examples/hfl/config/Singa-HFL.iml
1. Add .gitignore
2. Add iml config file
=> Add config folder for the HFL example

examples/model_selection/TRAILS-Database-Native-Model-Selection/internal/pg_extension/sql/pg_extension.sql
Update the pg_extension sql file for TRAILS model selection
=> Update the pg_extension sql file for TRAILS model selection

examples/model_selection/Trails/README.md
Add descriptions for the dependencies
=> Add descriptions for the dependencies

examples/msmlp/native.py
=> Add the model file for msmlp

examples/cnn_ms/run.sh
Add the running script for cnn ms
=> Add the running script for cnn ms

examples/msmlp/model.py
Add the model file for the msmlp
=> Add the model file for the msmlp

examples/cnn_ms/train_cnn.py
Add training cnn implementations
=> Add training cnn implementations

examples/cnn_ms/train_mpi.py, examples/model_slicing_psql/README.md
Initialize dynamic model slicing examples.
=> Init dynamic model slicing examples, add README.md

examples/cnn_ms/train_cnn.py
This PR introduces several updates to the data types and tensor operations used in our training modules. The goal of these updates is to enhance the efficiency and accuracy of our machine learning models.
=> Update the data types and tensor operations for training

examples/ms_model_mlp/model.py
Add implementations for the new loss function
=> Add implementations for the new loss function

examples/ms_model_mlp/native.py
Add implementations of the native model for the ms model example
=> Implementations of the native model for the MS model example

examples/cnn_ms/README.md
Add the README.md file for the cnn ms example.
=> Add README.md for the cnn ms example

examples/cnn_ms/autograd/cifar10_multiprocess.py
Add the autograd file for multiprocessing
=> Add the autograd file for multiprocessing

examples/cnn_ms/autograd/xceptionnet.py
Add the autograd implementation of xceptionnet
=> Add the autograd implementation of xceptionnet

examples/cnn_ms/autograd/resnet_dist.py
Add the distributed version of the model
=> Add the distributed version of the model

examples/cnn_ms/autograd/sparsification_mnist.py
Add the sparsification version of the model
=> Add the sparsification version of the model

examples/cnn_ms/autograd/resnet_cifar10.py
Add implementations for the autograd resnet cifar-10
=> Add implementations for the autograd resnet cifar-10

examples/cnn_ms/data/download_mnist.py
This pull request adds the download implementations for the benchmark dataset.
=> Add the download implementations for the benchmark dataset

examples/cnn_ms/data/cifar10.py
=> Add a benchmark dataset for testing the model selection

examples/cnn_ms/msmlp/native.py
1. Add examples folders
2. Add the implementation for the native model in the cnn ms example
=> Add the implementation for the native model in the cnn ms example

examples/cnn_ms/msmlp/model.py
Add the msmlp model implementation for the cnn ms example
=> Add the msmlp model implementation for the cnn ms example

examples/cnn_ms/msmlp/model.py
Add the implementation for the SumError class
=> Add the implementation for the SumError class

RELEASE_NOTES
Update the RELEASE_NOTES for v4.3.0
=> Update the RELEASE_NOTES for v4.3.0

examples/cnn_ms/msmlp/model.py
Add the SumErrorLayer class for the msmlp model
=> Add the SumErrorLayer class for the msmlp model

examples/trans/README.md
1. Add the readme file for the Transformer example
2. Add Machine translation model using Transformer Example
=> Add the readme file for the Transformer example

examples/trans/model.py
Add implementations of the Transformer model.
=> Add implementations of the Transformer model

examples/trans/data.py
Add the implementation of data processing for the transformer example
=> Add the implementation of data processing for the transformer example

examples/trans/README.md, java/pom.xml
Update license headers for V 4.3.0
=> Update license headers for V 4.3.0

examples/cnn_ms/msmlp/model.py
Update the model.py for the msmlp example
=> Update the model.py for the msmlp example

examples/trans/README.md, examples/trans/data.py, examples/trans/run.sh, examples/trans/train.py
Update the data processing for the benchmark dataset
=> Update the data processing for the benchmark dataset

examples/msmodel_mlp/native.py
This pull request adds the implementation of the native model.
=> Add the implementations of native model

examples/malaria_cnn/train_cnn.py
add main file for malaria cnn training
=> add main file for malaria cnn training

examples/healthcare/Malaria_Detection/README.md, examples/healthcare/Malaria_Detection/data/malaria.py, examples/healthcare/Malaria_Detection/model/cnn.py, examples/healthcare/Malaria_Detection/model/mlp.py, examples/healthcare/Malaria_Detection/run.sh, examples/healthcare/Malaria_Detection/train_cnn.py
Create the healthcare folder for healthcare models
=> Create the healthcare folder for healthcare models

examples/healthcare/Hematologic_Disease/transforms.py
Add the transforms.py file for the hematologic disease example
=> Add the transforms.py file for the hematologic disease example

examples/healthcare/models/malaria_net.py
Create the models folder for the healthcare model zoo
=> Create the models folder for the healthcare model zoo

examples/healthcare/data/malaria.py
Create the data folder for the healthcare model zoo
=> Create the data folder for the healthcare model zoo

examples/healthcare/application/TED_CT_Detection/README.md, examples/healthcare/application/TED_CT_Detection/model.py, examples/healthcare/application/TED_CT_Detection/train.py
The prototype layer and loss are implemented with Singa tensor and autograd. The corresponding dataset cannot be released due to privacy issue and a training script on cifar-10 is provided.
=> Add convolution prototype network used in TED project

examples/healthcare/application/Diabetic_Retinopathy_Classification/README.md, examples/healthcare/application/Diabetic_Retinopathy_Classification/train.py
Add the training file for diabetic retinopathy classification
=> Healthcare - Diabetic Retinopathy Classification 

examples/healthcare/data/cifar10.py
Add a sample test dataset for the TED CT Detection
=> Add a sample test dataset for the TED CT Detection

examples/healthcare/application/Hematologic_Disease/train_cnn.py
This pull request introduces a new training script designed for predicting hematologic diseases. The script includes data preprocessing, model architecture, training loop, and evaluation metrics, aiming to enhance predictive accuracy and streamline the workflow for disease classification.
=> Adding the training script for the hematologic disease prediction

examples/healthcare/application/Hematologic_Disease/run.sh
Add the running script for the Hematologic Disease Application
=> Add the running script for the Hematologic Disease Application

examples/healthcare/application/TED_CT_Detection/README.md
- update TED_CT_Detection README.md and give a more clear running instruction
=> update TED_CT_Detection README.md

examples/healthcare/application/TED_CT_Detection/run.sh
The commit is to add the running script for the TED_CT_Detection.
=> Add the running script for the TED_CT_Detection

examples/healthcare/application/Diabetic_Readmission_Prediction/train.py
Add the implementation forthe  training file of the diabetic readmission prediction.
=> Support Diabetic readmission training

examples/healthcare/models/tedct_net.py
Update the implementation of model for the TED CT
=> Update the implementation of model for the TED CT

examples/healthcare/application/Diabetic_Retinopathy_Classification/run.sh
Add the running script for the diabetic retinopathy classification
=> Add the running script for the diabetic retinopathy classification

examples/healthcare/application/Diabetic_Disease/Diabetic_Readmission_Prediction/README.md
=> Update the readme file for the Diabetic Readmission Prediction

examples/healthcare/data/kidneydata.py
Add the dataset for the kidney disease prediction
=> Add the dataset for the kidney disease prediction

examples/healthcare/application/Kidney_Disease/train_kidney_mlp.py
Add the training file for the kidney disease prediction
=> Add the training file for the kidney disease prediction

examples/healthcare/models/cardiovascular_net.py
Add the implementation of the model for cardiovascular disease
- Implemented MLP class with forward and training methods
- Added support for different distributed optimization strategies
- Included create_model function for model initialization
=> Add the implementation of the model for cardiovascular disease

examples/healthcare/application/Cardiovascular_Disease/train_cnn.py
Add the implementation of the model for cardiovascular disease detection
=> Add the implementation of the model for cardiovascular disease detection

examples/healthcare/application/Diabetic_Disease/Diabetic_Readmission_Prediction/README.md, examples/healthcare/application/Kidney_Disease/README.md, examples/healthcare/application/Thyroid_Eye_Disease/README.md
Update the readme files for healthcare applications
=> Update the readme files for healthcare applications

examples/healthcare/application/Malaria_Disease/train.py, examples/healthcare/models/malaria_net.py
=> update malaria model

examples/healthcare/application/Hematologic_Disease/readme.md, examples/healthcare/application/Hematologic_Disease/run.sh, examples/healthcare/application/Hematologic_Disease/train.py, examples/healthcare/application/Thyroid_Eye_Disease/README.md, examples/healthcare/application/Thyroid_Eye_Disease/run.sh, examples/healthcare/application/Thyroid_Eye_Disease/train.py, examples/healthcare/data/bloodmnist.py, examples/healthcare/data/cifar10.py, examples/healthcare/models/hematologic_net.py, examples/healthcare/models/tedct_net.py
Update hematologic disease application and  thyroid eye disease application
=> Update hematologic disease application and  thyroid eye disease application

.asf.yaml
=> Upgrade the .asf.yaml file

examples/singa_peft/src/singa_peft/__init__.py
Add the init file for the implementation of PEFT
=> Add the init file for the implementation of PEFT

examples/singa_peft/examples/run.sh
Add the running script for the PEFT examples
=> Add the running script for the PEFT examples

examples/singa_peft/examples/data/mnist.py
Add the example data folder for SINGA peft
=> Add the example data folder for SINGA peft

examples/singa_peft/examples/test.py
Add the test script for the singa peft example
=> Add the test script for the singa peft example

examples/singa_peft/src/singa_peft/tuners/linear_lora/layer.py
Update the LinearLoRALayer Class
=> Update the LinearLoRALayer Class

examples/singa_peft/src/singa_peft/tuners/linear_lora/tuner.py
Add the implementations of tuner for the PEFT example
=> Add the implementations of tuner for the PEFT example

examples/singa_peft/examples/autograd/mnist_dist.py
Add the autograd implementations for the peft example
=> Add the autograd implementations for the peft example

examples/singa_peft/examples/model/alexnet.py
Add the model implementations for peft
=> Add the model implementations for peft

examples/healthcare/application/Candidiasis_Disease/run.sh
Add the running script for the candidiasis disease.
=> Add the running script for the candidiasis disease.

examples/healthcare/application/Candidiasis_Disease/train.py
Update the train file for the  candidiasis disease model
=> Update the train file for the  candidiasis disease model

examples/singa_peft/examples/autograd/cifar10_multiprocess.py
Add the multiprocess implementations for the singa peft
=> Add the multiprocess implementations for the singa peft
